baseurl = "https://www.steventammen.com/"
title = "Home"
theme = "spartan"
author = "Steven Tammen"
canonifyurls = true
paginate = 10

[indexes]
  category = "categories"
  tag = "tags"
  
[params]
  # Shown in the home page
  subtitle = "Writings from the mind of Steven Tammen. Occasionally comprehensible."
  googleAnalytics = "UA-123565799-1"
  #disqus = "steventammen"
  # CSS name for highlight.js
  highlightjs = "solarized-dark"
  # additional languages for highlight.js (for all pages)
  highlightjs_extra_languages = ["lisp", "r", "autohotkey"]
  dateFormat = "02 Jan 2006"

[blackfriday]
  fractions = false
  
[menu]

  # Shown in the side menu.
  [[menu.navigation]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
	

  [[menu.author]]
    name = "About"
    pre = "<i class='fas fa-user fa-fw'></i>"
    weight = 10
	identifier = "about-the-author"
    url = "/about-the-author/"
  [[menu.author]]
    name = "Resume"
    pre = "<i class='fas fa-file-pdf fa-fw'></i>"
    weight = 20
	identifier = "resume"
    url = "/resume.pdf"
  [[menu.author]]
    name = "CV"
    pre = "<i class='fas fa-file-pdf fa-fw'></i>"
    weight = 30
	identifier = "cv"
    url = "https://www.steventammen.com/CV.pdf"
  [[menu.author]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 40
	identifier = "contact"
    url = "/about-the-author/#contact"
#  [[menu.author]]
#    name = "Software"
#    pre = "<i class='fa fa-code fa-fw'></i>"
#    weight = 40
#	identifier = "software"
#    url = "/software/"
#  [[menu.author]]
#    name = "Nonfiction"
#    pre = "<i class='fas fa-book fa-fw'></i>"
#    weight = 50
#	identifier = "nonfiction"
#    url = "/nonfiction/"
#  [[menu.author]]
#    name = "Fiction"
#    pre = "<i class='fas fa-book fa-fw'></i>"
#    weight = 60
#	identifier = "fiction"
#    url = "/fiction/"
	

#  [[menu.content]]
#    name = "Pages"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 110
#    identifier = "pages"
#    url = "/pages/"
#  [[menu.content]]
#    name = "Reviews"
#    pre = "<i class='fab fa-youtube fa-fw'></i>"
#    weight = 120
#    identifier = "reviews"
#    url = "/reviews/"
#  [[menu.content]]
#    name = "Sources"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 130
#    identifier = "sources"
#    url = "/sources/"
#  [[menu.content]]
#    name = "Guides"
#    pre = "<i class='fab fa-youtube fa-fw'></i>"
#    weight = 140
#    identifier = "guides"
#    url = "/guides/"
#  [[menu.content]]
#    name = "Life Hacks"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 150
#    identifier = "life-hacks"
#    url = "/life-hacks/"
#  [[menu.content]]
#    name = "Weekly Links"
#    pre = "<i class='fas fa-file-alt fa-fw'></i>"
#    weight = 160
#    identifier = "weekly-links"
#    url = "/weekly-links/"
  [[menu.content]]
    name = "Blog"
    pre = "<i class='fas fa-file-alt fa-fw'></i>"
    weight = 170
    identifier = "blog"
    url = "/blog/"
	
	
#  [[menu.site]]  
#    name = "About"
#    pre = "<i class='fas fa-sitemap fa-fw'></i>"
#    weight = 210
#    identifier = "about-the-site"
#    url = "/about-the-site/"
#  [[menu.site]]
#    name = "Categories"
#    pre = "<i class='fa fa-folder fa-fw'></i>"
#    weight = 220
#    identifier = "categories"
#    url = "/categories/"
#  [[menu.site]]
#    name = "Subject Index"
#    pre = "<i class='fas fa-list fa-fw'></i>"
#    weight = 230
#    identifier = "subject-index"
#    url = "/subject-index/"
#  [[menu.site]]
#    name = "Settings"
#    pre = "<i class='fas fa-cog fa-fw'></i>"
#    weight = 250
#    identifier = "settings"
#    url = "/settings/"
#  [[menu.site]]  
#    name = "Mailing List"
#    pre = "<i class='fas fa-envelope fa-fw'></i>"
#    weight = 260
#    identifier = "mailing-list"
#    url = "/#subscribe-to-the-mailing-list"
#  [[menu.site]]  
#    name = "RSS"
#    pre = "<i class='fas fa-rss fa-fw'></i>"
#    weight = 270
#    identifier = "rss"
#    url = "/rss"

	
#  [[menu.community]]
#    name = "Forums"
#    pre = "<i class='fab fa-discourse fa-fw'></i>"
#    weight = 300
#	identifier = "forums"
#    url = "/pages/about-the-author/"
#  [[menu.community]]
#    name = "Discord"
#    pre = "<i class='fab fa-discord fa-fw'></i>"
#    weight = 310
#	identifier = "discord"
#    url = "/discord"
	