[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.52"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "https://community.steventammen.com/*"
to = "https://community.bibledocs.org/:splat"
status = 301
force = true
