#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: pages

#+TITLE: "Learning Styles"
#+DATE: 2018-03-18T17:53:47-04:00
#+HUGO_CATEGORIES: "Science/Knowledge"
#+HUGO_TAGS: "metalearning" "neuroscience"
#+HUGO_CUSTOM_FRONT_MATTER: :inprogress true

* Print as Superior Medium for Information Transmission

- Almost all people read faster than they can comfortably listen to someone speak. (Ever try reading the transcript of a podcast and then listening to it at 2.5x speed? It should make what I'm talking about obvious). Reading is also much faster than taking in most types of complex/overly difficult information in some sort of visual form (e.g., a table).

  - It's also worth pointing out that nothing stops writers from including charts, graphs, pictures, etc. when they are superior to text for conveying some particular information... it's just the idea of learning /everything/ (or even just a majority of things) through visual media that is silly and contrary to everday experience.

- The visual structure of texts helps give your brain a physical analogue for the mental map it is forming. Particularly if the texts take pains to structure themselves in a meaningful way (which they should).
- Print makes it easy to go back to compare/contrast information. Since learning is relational ("neurons that fire together wire together"), this helps you make more neural connections, and therefore learn faster. (At least theoretically). It is much more difficult to go back to compare/contrast information with audiobooks.

While many people argue for so-called "learning styles" there is still [[https://en.wikipedia.org/wiki/Learning_styles#Criticism][a lack of determinative evidence]]. In my opinion, it is pretty obvious that /everyone/ learns better when more of their senses are activated (which has a neurobiological explanation: the more neurons involved in learning, the better the relational connections, and the stronger the recall). However, I have no philosophical problem with some people having more developed brain structures in some areas than others (due to genetic reasons), with corresponding increases in base effectiveness for some methods of learning. I'm just highly skeptical that any such differences could possibly make up for the huge advantages reading has inherently... and also highly skeptical that these developed brain structures are immutable. My guess is that so-called "kinesthetic learners" could /become/ "read/write learners" simply by reading and writing more, thereby increasing the brain matter dedicated to these functions. So the question really shouldn't be "what type of learner are you?" but "what kind of learner should you become /in order to learn most effectively/?"... which is almost certainly the kind that involves reading.

Using this logic, it would make sense if most people learn best through some combination of reading and other media as appropriate. Current data seems to support this.
