#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: pages

#+TITLE: "Rain Gear"
#+DATE: 2018-03-18T17:58:06-04:00
#+HUGO_CATEGORIES: "Gear"
#+HUGO_TAGS: "essential gear" "gear cluster" "clothing"
#+HUGO_CUSTOM_FRONT_MATTER: :inprogress true

* Waterproofing

- Don't need it when it's not raining, extra unnecessary material

  - Additionally, want to be able to take off wet layers after rain ⇒ they should be separate
  - Additionally, having waterproof/windproof shell separate from thermal layer means that it is more versatile and can be used across a wider temperature range than a single thermal layer that is waterproof/windproof. Argument could be made that it's one more jacket to carry around for cold, wet situations, but what if it is cold and rainy in the morning and hot and rainy in the afternoon? You'd have to carry around an extra jacket for the hot situation if you only had one thermal layer.
  - If waterproofing fails you replace a cheaper rain jacket rather than a more expensive thermal insulating one (with down, etc.): idea of separability.

- Abrasion resistance: better to have stronger materials on outside layer

  - But don't want any wet layers of clothing for continual wear after rain, so waterproof layer must go on outside

    - Would also take longer to put on at rain onset (if layers had to be reshuffled).
    - Would also get things in pockets wet, if applicable

- For clothing thermal insulation is important: dry warmth layers insulate better than wet warmth layers. This is a more important consideration than abrasion resistance for clothing, so therefore, waterproof layer on outside for clothing. Inherent tradeoff between waterproofing and breathability: wearing waterproofed gear during situations when you don't need the waterproofing will be hotter than well design breathable/wicking materials not design to be waterproof. Thus, don't want it unless you need it.

* Main Idea

Rain jacket + rain pants most efficient rain gear if backpacks are waterproof: don't obstruct movement/ flap about (ponchos) or require a hand to use/get messed up by wind (umbrellas).

- Jackets (how effective is DWR?)

  - Shell is better
  - Don't need extra material most of the time
  - Can get rid of wet outer layer when not in rain/coming inside
  - Replaceable without replacing warmth later; separation of features
  - Don't need to maintain DWR and use chemicals

- Waterproof jacket/pants better than umbrella

  - Full coverage; legs/feet stay dryer
  - Not affected by wind or rain at an angle
  - Keeps hands free

- Waterproof jacket/pants better than poncho

  - Can replace one component without replacing other; separation of features
  - No extra material to flap about in wind or get caught on things
  - Full leg coverage instead of partial (depending on poncho type)
  - Disadvantage: may not be able to use jacket/pants as a tarp like you could with a poncho

- Better to keep pack waterproofing separate from jacket

  - What happens if you don't need backpack but need the jacket? Extra material would get in the way.

- Pack covers insufficient

  - Pack cover doesn't protect inside contents from as many circumstances as a good dry-liner.

    - Heavy rain coming in between spaces between pack cover and back/straps/etc.
    - Pack falls into water (puddle, river, etc.)

- Internal dry liner vs external waterproofing

  - Problem of making openings watertight??? Tivi Zippers?
  - Hassle of messing with interior dry bag vs just one zipper?


