#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: pages

#+TITLE: "Work Environment"
#+DATE: 2018-03-18T18:03:28-04:00
#+HUGO_CATEGORIES: "Gear" "Productivity/Efficiency"
#+HUGO_TAGS: "essential gear" "rsi prevention"
#+HUGO_CUSTOM_FRONT_MATTER: :inprogress true

* Overview

Your work environment is simply the collection of objects that play a role in your work. For most of us, that means a keyboard, a monitor, a desk, a chair, and some way to manage sound (headphones/earplugs). Each element of the work environment is briefly discussed below, but ultimately you should do more research. Don't just take my word for these things.

* Keyboard

Please have a look at [[https://steventammen.com/keyboards/][this page]].

* Monitor

You need to make sure you are not twisting or tilting your head to look at your screen, and this includes laptop screens. Ideally your eye height should be at some point in the top quarter of your display, and the screen should be adjusted in such a way that it allows you to keep your back straight instead of slouched. You should adjust screen brightness according to your surroundings: if in a bright room, you can keep it high, but dim it as light levels decrease. Try to put your monitor in a place that minimizes glare (so not across from a window or lamp). Check whether or not your display uses pulse width modulation (PWM) to dim, since its high frequency flicker can give some people headaches.

You should also tone down the blue light coming out your screen, especially towards evening and sundown. I use and recommend [[https://justgetflux.com/][f.lux]] for this purpose, but there are other software programs with similar functionality. Having a warmer light tone helps minimize technology's disruption of your circadian rhythm and melatonin levels.

If you buy a new monitor there are some basic things to keep in mind. For LED backlit LCD displays, in general, IPS panels are better than VA panels, and VA panels are better than TN panels. OLED (organic light emitting diode) displays are better than all LCD displays because they provide better contrast and have a "true black." Curved monitors better utilize our natural field of vision, but are much overhyped, especially since the curvature doesn't really matter very much until you get to 40+ inches.

Before you decide to upgrade your monitor, you ought to make sure you are using virtual desktops effectively (built into Mac OSX, Windows, and many Linux distributions), as well as a good tiling window manager (e.g., [[https://www.nurgo-software.com/products/aquasnap][AquaSnap]] for Windows). Many people have been tricked into thinking they need multiple monitors when they really wouldn't for their use case if they would learn how to better manage their programs.

If you do decide that you could efficiently make use of more screen real estate, you should consider getting a large (greater than or equal to 40 inches) 4k monitor/TV instead of stringing together multiple smaller monitors, especially if your graphics card will support 4:4:4 Chroma 4k @60Hz. Vertical height is more important than horizontal space for virtually all computing activities other than watching videos (e.g., reading web pages, spreadsheets, coding), and 4k's 2060 vertical pixels let you take advantage of this fact. You also avoid bezels by having one screen instead of two or three.

* Desk

Your desk should allow for comfortable amounts of legroom. The other important desk consideration is how it allows you to position your keyboard; your "elbow angle" when typing should be roundabout 90 degrees (perhaps a little greater), your wrists should be straight, and your shoulders and arms should be relaxed. A keyboard tray with a negative incline is ideal, though they tend to be rather expensive. If your desk forces you to type with bent wrists and an acute elbow angle you are setting yourself up for RSI.

Standing desks are a bit less important than their marketing would have you believe, but they are still ideal, especially the kind you can adjust up and down quickly with motors. When we stand we naturally shift our weight from foot to foot and vary our posture to never strain one particular muscle group. When we sit, by and large, we maintain the same position for hours, which can lead to muscle tension and health problems. If you do use a standing desk, try to go barefoot as much as circumstances allow.

* Chair

Your chair should allow you to maintain the arm position discussed above. It would be good if it also forced spinal curvature with lumbar support, and had armrests to rest your arms on /when you are not typing/. In general, you should forgo cushioned squishy chairs for those that possess a moderately rigid curve that matches the curvature of your spine. Anything that allows or even encourages poor posture should be avoided. If you have the money to spare, a fully adjustable chair like the Herman Miller Aeron or SteelCase Leap would be a good purchase since such a chair would allow for custom-tailored ergonomics.

Some people advocate using a medicine ball in place of a chair. While this makes consistent postural variation easier to keep up (and allows for some good stretching during breaks and/or micro-breaks), most people won't have a strong enough core to maintain the rigidity of their spine for long periods of time. If you are too weak to maintain good posture for your desired use duration, this should be avoided until such a time as you can. I'm planning on doing more research about this sort of thing ("chairs and sitting are bad and are responsible for many health problems -- medicine balls and other novel support systems are always superior") to see how much of it is scientifically verifiable, and how much is just marketing.

Slouching on your couch with your laptop/tablet or laying on your bed with your laptop/tablet are bad habits that should be kicked. Good posture will never be achieved without a zero tolerance policy for bad posture.

* Headphones or Earplugs

You should invest in a high quality (~30 dB blocking) pair of noise isolating headphones or earplugs -- either of the in-ear variety or the over-ear variety. I would suggest headphones rather than earplugs because you can use them for listening to things if you ever decide you want to (but they'll typically be more expensive), and the in-ear variety because they're more portable than over-ear headphones (and so can pull double-duty when working out, riding a motorcycle, etc.). Custom molded headphones are preferable to off-the-shelf headphones because they block more sound, fit better, and are more comfortable.

Whether or not you listen to music is a personal call. Theoretically, music takes up some brain-power (especially vocal music, which activates the language-processing part of the brain), but it can also enhance productivity by positively altering mood. Even if you don't listen to music, it is still important to manage sound with earplugs, since humans are automatically programmed to pick up on changes in background noise. The fewer novel auditory stimuli you are exposed to (particularly of the extreme variety -- in pitch, amplitude, etc.), the better you'll be able to focus your attention.
