#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: links

#+TITLE: Fallibility of Human Reason
#+DATE: 2018-03-18T18:01:12-04:00
#+HUGO_CATEGORIES: "Philosophy"
#+HUGO_TAGS: "rationality" "thought patterns"
#+HUGO_CUSTOM_FRONT_MATTER: :inprogress true

* Understanding The Fallibility of Human Reason

One of the most important things to do after questioning what people are telling you is to question your own beliefs. We all like to think of ourselves as rational, competent thinkers. The truth is that humans are predisposed to blind spots in our thought, and are, on the whole, incapable of viewing reality as it really is.

*Main Idea:* As humans, we are biased and irrational in many ways, with a large proportion of these being outside of most people's awareness. Consequently, many people are far more sure of themselves and their beliefs than they should be.

*Practical Applicability:* Learning how to examine your own biases, irrational beliefs, self-justifications, and so forth is critical for good decisionmaking. Learning about your own biases is also helpful in cultivating empathy for others.

** [[http://www.gutenberg.org/ebooks/1656][Plato's /Apology of Socrates/]]

Book Main Idea: On trial for supposedly corrupting the morals of the youth (among other things), Socrates defends himself by explaining how his quest to prove the Oracle of Delphi wrong in its assessment of him as the wisest man led to him questioning various experts who thought that they had knowledge, only to find out that they had no idea what they were talking about.

Book Practical Applicability: A classic work, Plato's /Apology of Socrates/ gives one of the West's most powerful thinker's views on the arrogance of human knowledge. (How much of this is Socrates and how much is Plato is ultimately irrelevant: the so-called [[https://en.wikipedia.org/wiki/Socratic_problem]["Socratic question"]] in no way dimishes the applicability of the arguments in this text). The /Apology/ is useful mostly as an introduction to the idea that most of what people think they know breaks down under intense questioning, and that society should appreciate people like Socrates, people who ask hard questions and tear down false knowledge structures, even though they may be supremely irritating.

** [[https://www.amazon.com/How-Know-What-Isnt-Fallibility/dp/0029117062][/How We Know What Isn't So: The Fallibility of Human Reason in Everyday Life/]]

Book Main Idea: In a rapidly changing world, the biases and stereotypes that help us process an overload of complex information inevitably distort what we would like to believe is reality.

Book Practical Applicability: This book is a good introduction to some of the biases and irrational thought patterns that are present in everday life. Becoming aware of one's own biases and irrational beliefs is more than half the battle to overcoming them, so getting a general overview of common biases and irrational beliefs is an effective first step in improving the rationality of one's thought.

** [[https://www.amazon.com/Mistakes-Were-Made-but-Not/dp/0544574788/][/Mistakes Were Made (but Not by Me): Why We Justify Foolish Beliefs, Bad Decisions, and Hurtful Acts/]]

Book Main Idea: Self-justification and rationalization are more powerful than most people can imagine, and occur with frightening regularity.

Book Practical Applicability: Like biases and irrational beliefs above, learning about self-justification and rationalization is more than half the battle to overcoming them, making this book another good option for improving the rationality of one's thought. This book also serves as a chilling reminder that people don't suddenly wake up and find themselves evil, but slip into moral decay through a long string of almost imperceptible self-justifications and rationalizations. In other words, it reminds one of the banality of evil.
