#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: pages

#+TITLE: "English Letterforms"
#+DATE: 2018-03-18T17:50:11-04:00
#+HUGO_CATEGORIES: "Productivity/Efficiency"
#+HUGO_TAGS: "handwriting" "rethinking standards"
#+HUGO_CUSTOM_FRONT_MATTER: :inprogress true

* Cursive Vs. Print

- Because everything in print uses uses print letterforms, in our day and age, we are more accustomed to /reading/ print letters than cursive letters.
- Just think about it logically: if most of what we read uses print letterforms, it just makes intuitive sense that we will be more used to reading them, and therefore faster and better at recognizing them. (I.e., they will be more legible to us).

  - See [[http://lianza.org/files/cursivevsprint.pdf][this paper]] (Note: not peer reviewed as far as I can tell, but also no glaring methodological flaws).

- There is also some evidence that our perception of letters is conditioned by our formation of them during handwriting (but not typing, interestingly). In other words, handwriting letters actually makes us better readers. It would stand to reason that the closer the letters we form are to the letters we read, the more impactful the effect.

  - See the [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3780305/#s1title][introduction]] of [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3780305/][this paper]].

- Due to the nature of writing, we generally read the things we have written more than once. Therefore, within reason, it is more important to optimize for legibility/readability than writing speed.

  - The one exception to this general principle is for those who must frequently handwrite things at high speed for whatever reason. (Practiced typists can get up to 100 WPM and practiced stenographers up to 225... practiced handwriters max out around 30, leading one to ask why handwriting is even being considered for use in situations that demand speed). In this case, it might be better to sacrifice legibility/readability for speed (which generally means connecting more and using letterforms with less strokes but reduced recognizability). Gregg shorthand or an extensive personal briefing system for fast scenarios + the letterforms shared below for everything else would make even more sense, however. (In my opinion).

- Strict printing is slower than connected writing since it requires frequent lifts and drops -- which add time, however little it might be. For this reason, it makes the most sense to design a writing system that is essentially "connected print" -- connecting all the letters that it makes sense to, while leaving those that significantly reduce legibility unconnected. This might sacrifice a little bit of readability/legibility, but will gain speed and fluidity of writing (less writing pressure, more relaxed hand, greater ability to write with arm/wrist rather than fingers, etc.).

* Basic Design Methodology

1. Come up with different variants of regular print letterforms
2. Evaluate forms based on

   1. Travel distance ("ink consumed")
   2. Number of distinct direction changes (corners/180 degree turns/"direction-changing loops" rather than wide loops)
   3. Distinguishability from other letters/letter combinations
   4. Recognizablity, i.e., how easy it is to tell that the form represents =___= print letter
   5. Broad detail vs. fine detail (broad detail is better for faster speeds/enables faster speeds)

3. Pick the best form for each letter

* Dotting And Crossing

- Cross t's and f's by using the stroke as a connector to the next letter
- Dot i's and j's during their formation: slavishly maintaining a no-lift policy (i.e., dotting at the ends of words or sentences) leads to unecessary travel distance and a disruption of thought.

* TODO: Other Section Ideas

- Slant?
- Letter/word spacing?
- Replicating computer italics for handwriting use?
