#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: pages

#+TITLE: "Pencils"
#+DATE: 2018-03-18T17:57:15-04:00
#+HUGO_CATEGORIES: "Gear"
#+HUGO_TAGS: "writing gear" "essential gear"
#+HUGO_CUSTOM_FRONT_MATTER: :inprogress true

* Basic Idea

- From a practical standpoint, mechanical pencils are better than wood pencils (worst) and leadholders (not quite as bad, but suboptimal for everyday use outside of a few specific applications).
- You have to sharpen wood pencils, and you get wood shavings as well as lead shavings. Additionally, if you are writing with a soft lead (as you should be), it will dull very quickly and you will have to sharpen often. Additionally, the weight/length of the pencil will change as you sharpen it more and more rather than staying consistent (decidedly bad --- you will have to change your grip and accommodate many different physical configurations instead of just getting used to one).
- Lead holders have the same sharpening problems as wood pencils (minus the wood shavings --- generally lead holders are easier to sharpen and less messy overall), and you still run into the problem of having to constantly resharpen, especially if you use soft lead. Leadholders have two primary advantages over wooden pencils: they give you the ability to retract the tip so it doesn't get damaged or stab you, and 2) they stay the same size and (relatively) the same weight instead of changing over time.

* Width

- see [[https://steventammen.com/pencil-leads/#lead-width]]

* Advancing mechanism

- Of the options available (back click, side click, shaker, auto-feed), I think a /well designed/ side click wins every time.
- Back clicks require you to move your hand out of writing position in order to extend the lead.
- Shakers let you keep your hand in writing position, but you need to move the pencil fairly significantly to get the mechanism to actuate.
- Well designed side clicks (i.e., those that let you keep your thumb on the advance mechanism continuously) let you keep your hand in writing position and advance lead without undue movement. Once you get good at timing, you can generally advance lead between words with minimal delay.
- Auto-feed pencils work by making the lead guard scrape against the paper to release more lead. The scraping mechanism has some distinct disadvantages: 1) it can limit writing angles (because very little lead is out at any given time), 2) you basically have to run out of extended lead to get more lead, which leads to line inconsistency and scratchiness. On the other hand, you rarely ever break lead. (Which isn't a huge pro in my opinion because once you learn how to write with your arm with minimal pressure you never break lead anyway).

* Research: Lamy 2000 (Pencil balance)

- [[https://www.reddit.com/r/pencils/comments/2k3trp/pentel_graphgear_1000_uni_ball_kuru_toga_or/]]
- [[https://www.reddit.com/r/pencils/comments/3yri78/my_top_3_lists_for_every_price_point_extensive/]]
- [[https://www.reddit.com/r/pencils/comments/3irp1w/lamy_2000_vs_rotring_600_or_800/]]
- [[https://www.youtube.com/watch?v=KdSQfCARXCg]]
- [[http://davesmechanicalpencils.blogspot.com/2006/10/lamy-2000-mechanical-pencil-review.html]]
- [[http://davesmechanicalpencils.blogspot.com/2007/08/poll-1-lamy-2000.html]]
- [[http://davesmechanicalpencils.blogspot.com/p/my-top-5.html]]
- [[http://www.fountainpennetwork.com/forum/topic/99987-lamy-2000-mechanical-pencil/]]
- [[http://www.fountainpennetwork.com/forum/topic/42931-lamy-2000-pencil/]]
- [[http://www.fountainpennetwork.com/forum/index.php/topic/227631-lamy-2000-and-the-origins-of-lamy-design/]]
- [[http://davesmechanicalpencils.blogspot.com/2009/09/lets-talk-mechanical-pencils-with-lamy.html]]

* My Pick

- [[http://www.pentel.com/store/quicker-clicker-mechanical-pencil-original-config][Pentel Original Quicker Clicker]] (discontinued but available on eBay)
