#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: projects

#+TITLE: "Language Layers"
#+DATE: 2018-04-25T00:32:11-04:00
#+HUGO_CATEGORIES: "Computers/Software"
#+HUGO_TAGS: "greek" "unicode" "keyboard layouts"

* [[https://www.steventammen.com/projects/language-layers/language-layers.zip][Download current release (Windows only)]]

The header above is a link to a .zip archive of this project. As long as you have AutoHotkey installed (download it [[https://autohotkey.com/download/][here]]), you can unzip this archive wherever you like, and double clicking the file =remap.ahk= should start the program. (You can exit the program by right clicking it in the system tray and selecting "Exit").

* Subscribing to updates and staying informed

I have created a mailing list you can subscribe to if you are interested in staying informed of what is going on in the life of this project. Emails are rather infrequent and only for important updates. You may sign up using this form:

#+begin_export html
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://steventammen.us18.list-manage.com/subscribe/post?u=8975ea5632e637433df8c5866&amp;id=7ae9d95967" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe to the mailing list</h2>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_8975ea5632e637433df8c5866_7ae9d95967" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<!--End mc_embed_signup-->
#+end_export

* Beta testing

Beta testing is now live, and anyone who has the time and inclination can fill out a [[https://goo.gl/forms/qO4hMc4KnL6xTfxA3][Google form survey]] regarding the current project state. This form will remain open until such a point as I feel that the project has stabilized enough to start packaging the code as stable releases.

People who wish to Beta test probably ought to read several of the sections in the [[https://github.com/BlizzardWorks/language-layers/blob/master/README.org][project's Readme file]] before starting:

- [[https://github.com/BlizzardWorks/language-layers/blob/master/README.org#installation-instructions][Installation Instructions]]
- [[https://github.com/BlizzardWorks/language-layers/blob/master/README.org#usage-instructions][Usage Instructions]]
- [[https://github.com/BlizzardWorks/language-layers/blob/master/README.org#customization-instructions][Customization Instructions]]

* Update #1: 6/12/18

Today, I created a post about the [[https://www.steventammen.com/posts/initial-greek-survey-analysis/][survey results]], and informed people on the mailing list. I also added sections to the README of the [[https://github.com/BlizzardWorks/language-layers][project's GitHub repository]] about installing and using the in-progress Greek script, and contributing to the project.

* Update #2: 7/6/18

Today I added sections in the project's Readme describing how to install, use, and customize the software. I also created a second Google form to gather user feedback on the current project state in a round of Beta testing, and added a download link to this page for a pre-packaged .zip archive of the software in its current iteration. People on the mailing list were informed about all of this.


# Put at end to avoid conflicts with scrollspy TOC. ???
#+begin_export html
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
#+end_export
