#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: posts

#+TITLE: An Amazon Customer Service Experience
#+DATE: 2018-11-26T21:07:04-05:00
#+HUGO_CATEGORIES: "Productivity/Efficiency"
#+HUGO_TAGS: "online shopping" "Amazon" "business ethics"

* Why I like Amazon in general

I have essentially stopped buying things from local stores (excepting groceries) unless I absolutely have to because I was not keeping track of something and ran out. I have been an Amazon Prime member for several years now, and have found the convenience of ordering things online to be very positive.

I certainly don't get dogmatic about this (I have family members that still like to make store runs for things), but here are some of the reasons why I really like shopping on Amazon:

- Ordering from Amazon saves me time since I just click a couple buttons and two days later things arrive. So long as I am paying attention, I never really need anything faster than this. I don't have to drive places, spend time navigating a big maze-like store, deal with checkout lines, etc.
- Ordering from Amazon lets me buy a bunch of different kinds of things all in one go. No longer does one have to go to an art supply store, a gardening store, Walmart, and a sports outlet to get all the things. Usually I wait until I have a somewhat-long list of things I need, and place a single larger order.
- Ordering from Amazon lets me easily see reviews for products. If I am ever buying something big I do my own independent research (reading blogs, review sites, professional opinions -- such as the usually excellent writeups found on [[https://thewirecutter.com/][Wirecutter]] and [[https://www.rtings.com/][Rtings.com]] -- etc.), but for more mundane things like paper towels, toothpaste, sticky notes, etc. I have never had Amazon reviews fail me. I'm sure there is some sketchy review-stacking going on in certain areas (not-so-transparent paid reviews and what have you), but usually Amazon is pretty good about stamping out truly blatant cases. I have been shopping for smaller things on Amazon for quite a while now, and as long as I make sure what I'm buying is actually what I want and a good solution for my use-case, I have found that highly-reviewed things with lots of reviews (say, more than 200) are in fact good-quality products.

All this to say, I really like Amazon in general, and have found it to be a good solution according to my shopping habits. YMMV, of course.

* Negative perceptions of Amazon

I have seen a lot of blowback against Amazon since I've been using the service. For example:

- Cries of monpolization
- Complaints that Amazon is stamping out brick-and-mortar stores
- Reports of Amazon abusing their enormous throughput to twist the arms of shippers like UPS and Fedex
- Accusations regarding exploitative working conditions

I don't pretend to know everything about all cases. I'm sure Amazon is not unconditionally good or anything like that. But it has always seemed to me that big companies like Amazon (and Microsoft, Google, Facebook, etc.) get roasted by the press and certain corporate interest groups for any mistake they make.

I am all for more transparency, ethical treatment of all employees (bottom to top), and healthy competition -- all things that Amazon fails in from time to time. But think it's important to keep balance when judging corporate behavior. In other words, I think it's OK sometimes to say "You know what? No company is absolutely perfect (or even close). But I'm not ashamed to say that XYZ company is working well for me."

So that's what this is I guess. An N=1 example of why I think that Amazon, despite some of the black eyes it has had over the years, is not /only/ worthy of scorn and condemnation.

What do I mean?

* The postal service and my boxes

I keep having USPS lose my boxes. Inexplicably, they will send them to another street address with the same number but a completely different street name and ZIP address (and when I say sometimes I mean sometimes in the plural -- it has happened multiple times in the last year). Sometimes they just disappear. Sometimes they will mark a package as delivered two days before it arrives. Etc.

To my total consternation, I had a shipment get marked as "delivered -- handed to someone directly" about two weeks ago with no sign of the box anywhere. I waited patiently hoping that it would sort itself out, but it never did. My landlord told me that he's been having this problem for a long time now, and none of his efforts to get it fixed via USPS have proved fruitful. Boo.

Anyway, my most recent Amazon box never arrived. It is quite likely that this is a USPS problem not an Amazon problem, but I was out ~$45 and figured I'd explain the situation and see what happened from there.

* The support conversation

#+BEGIN_VERSE
Steven
7:51 PM
I just submitted a "did not receive" request via the assistant for one item from a box that never arrived

7:51 PM
S | Customer Service
Hi Steven :)
I am extremely sorry to hear that you didn't received the item although it's marked as delivered.

Steven
7:52 PM
The status of the USPS delivery said it got delivered November 14th, but the package never arrived at my house. We have had problems in the past with USPS delivering things to the wrong address or simply seeming to lose packages.

7:52 PM
S | Customer Service
So you have not received both the items or either of them?

Steven
7:52 PM
None of the items in this particular shipment. The box never arrived.
It had items from two separate orders.

7:53 PM
S | Customer Service
Just to confirm you are referring to an items

(1) Quick Stacks Cups, 12 Sets Of Sports Stacking Cups Speed Training Game (Blue)  

(2) 5 Packs Tangle-Free Cable Turtle Organizer Case Earbuds Keeper Headphone Storage Case Cord/Wire Shortener Cable Wrap Winder Cord Reel Manage Case Char  

(3) Anker 7-Port USB 3.0 Data Hub with 36W Power Adapter and BC 1.2 Charging Port for iPhone 7/6s Plus, iPad Air 2, Galaxy S Series, Note Series, Mac, PC,  

Right ?

Steven
7:53 PM
Yes, those are the items.

7:54 PM
S | Customer Service
Thanks for confirming.

May I know if you have checked for the package in your surroundings or may it be with your neighbors?

OR Is it possible that a family member of yours might have received the package on your behalf and forgot to inform you?

Steven
7:54 PM
I have checked with all other individuals that live in the house, checked next door with neighbors that I know, and also checked with the people that live at a house with a similar address that have received some of our mail in the past due to post office mistakes.
Nobody has seen the package, even though it says it was handed off directly.

7:55 PM
S | Customer Service
Thanks for information.

I will forward this concern to the appropriate team to investigate and will make sure that this mistake will not be repeated in future.

To help you in this case I am not able to send you the replacement of this item as this item is sold by 3rd party seller however I can issue a full refund.

Would that be okay with you?

Steven
7:56 PM
That would be great :). Thanks!

7:56 PM
S | Customer Service
You are most welcome :)

May I know which method would you prefer to get your refund?

Original payment method or Amazon gift card balance.

Steven
7:56 PM
Original payment method

7:56 PM
S | Customer Service
Sure thing.

Its done : )

I have issued your refund to original payment method.

The amount will reflect on your card statement within 3 to 5 business days.
Besides from this issue, Is there anything else I can help you?

Steven
7:57 PM
Nope, that's all. Thanks for your time and willingness to help.

7:57 PM
S | Customer Service
It was a pleasure assisting you with this. Thank you for contacting Amazon. Please click "End Chat" to close this window. Have a great day/night! : )
#+END_VERSE

* Discussion

That was it. The service rep simply took my word for it and I got my money back. I didn't/don't feel bad about asking, but to be perfect honest I was a bit surprised that this conversation went how it did. I think I was pretty up front that this was a shipping problem not an Amazon problem, but they just gave me a full refund regardless.

/This/ is why I like Amazon. Blind /naïveté/ or not (is my refund being paid for with the wage-slavery of thousands of workers who are abused? Borderline-unethical business practices?), this seems to me to be something beneficial for the consumer.

I guess it's worth pointing out that this is the second time I have asked for something like this (and I've been using Amazon for a while, like I said) -- so this isn't exactly a common pattern of behavior for me. I've returned my fair share of things (sometimes for no better reason than I changed my mind after doing more research), and have /never/ had a problem as long as I pay return shipping.

I'd be interested to hear other people's thoughts in the comments regarding any of the above: do you like online shopping? Is there a particular article I should read that irrefutably shows that I should take my business elsewhere since Amazon exploits XYZ people? Etc.
