#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: posts

#+TITLE: Getting a Second Pair of Skates: Thoughts
#+DATE: 2018-12-02T18:44:18-05:00
#+HUGO_CATEGORIES: "Gear"
#+HUGO_TAGS: "skating" "planning purchases"

* Background

I ordered the [[https://www.wizardskating.com/product/wizard-skate][Wizard NR110 skates]] a few months back since I wanted to pick up skating for exercise and fun. Despite liking the skates and all, there are lots of scary hills where I live, and I haven't ended up using them that much since I'm still kind of afraid of stopping. I need to change this.

* Why get a second pair of skates with smaller wheels?

** Learning

Smaller wheels, especially combined with the low center of gravity of the Trinity frames, give much more lateral stability than a 4x110 UFS system. This in turns makes balancing on one foot easier, which simplifies learning many things such as drag stops and powerslides (which both require balancing on one foot while using the other to brake).

They also are less stable (shorter wheelbase) and force the development of good skating form. The NR110 Wizard skates are so stable that you can get away with not leaning forward and having a good, centered weight distribution. (Of course, once you are an experienced skater, this is a feature not a bug: skating more upright is more relaxed and less fatiguing for casual cruising).

The lighter, shorter-wheelbase skates will also make learning/practicing crossovers easier. The lower forces put on the ankles and greater stability will also make learning jumps easier.

** After learning

Assuming a natural rocker on the 4x80 skates (see below), they will be very maneuverable. They will enable a different sort of skating than the Wizards: being lighter and shorter they will be more twitchy at speed, but better for tricks and things that require better handling.

The natural-rockered 4x80 skates will be better than the Wizards for jump-heavy urban skating and precise footwork, like the skating in Rollerblade's [[https://www.youtube.com/playlist?list=PLG0epWKWDn1ZDstULFH-m4nXtXr0BYF3E][80mm Freeskate Series]] and [[https://www.youtube.com/watch?v=f3vnWotWP2Y][this video]]. But they will be much slower, less stable at speed, and struggle more with bumps, cracks, and the like.

The basic justification for this second pair of skates is this: different tools for different jobs.

* The skates themselves

** Boot

[[https://www.powerslide.com/Powerslide-Next-Trinity-Boot-only][Powerslide Next Trinity Boot]].

- Plastic shell for stiffness/power transfer: you don't want squishy cloth skates ever! (See below on plastic vs. carbon).
- Moldable liner for comfort. (See below on Powerslide liners vs. Intuition).
- Trinity mount
- A removable front guard is a good idea that should be on all skates, in my opinion. Using hockey tape to protect the toes of your skates works, but it's a bit hackish.
- An adjustable back cuff is a good idea that should be on all skates, in my opinion.

** Frame

- A 4x80 flat Trinity-mount frame. It doesn't make sense to buy the Trinity frame option that lets you flip frame bolts to rocker the middle two wheels down for this particular skate configuration since urban freeskating does not want a banana rocker (and slalom does not want plastic boots). This will be discussed below. Spending the money to get a rockerable version doesn't make it worse or anything -- unless it makes wheel rotation harder; I'm not sure if the rockerable frame bolts interfere in wheel rotation or not. It would be something to look into.
- The Trinity mount gives superior control, power transfer, and lower overall skate height (at least for 4x80 skates where the bolts fall right on top of wheels -- I don't think it makes as big a different for big triskates). I think it makes lots of sense.

** Wheels

[[https://www.proskatersplace.com/shop/inline-skates/inline-skate-wheels/undercover-tiger-yellow-bullet-radius-86a-80mm/][Undercover 80mm 86a]], [[https://www.proskatersplace.com/shop/inline-skates/inline-skate-wheels/rollerblade-hydrogen-wheels-80mm-85a/][Rollerblade Hydrogen 80mm 85a]]

- Medium bullet profile for low rolling resistance (speed) and good maneuverability while still having some stability/grip for weird landing angles and spins etc. In other words, you want a bullet profile for 80mm freeskate wheels, but want it a little less pronounced than bigger wheels that are used for speed skating without as many jumps + more edge use. Fortunately, most bullet-profile 80mm wheels worth having fit this description.
- We want wheels with a good balance of ride comfort, speed, grip, durability, cost, and sliding ability. Here are some good Reddit links that talk about wheels:
  - [[https://www.reddit.com/r/rollerblading/comments/3hlhsp/hyper_concrete_g_80mm84a_or_rollerblade_hydrogen/][Hyper Concrete +G 80mm/84a or Rollerblade Hydrogen 80mm/85a : rollerblading]]
  - [[https://www.reddit.com/r/rollerblading/comments/7o7ovt/whats_the_difference_between_regular_wheels_and/][What's the difference between regular wheels and hydrogen wheels? : rollerblading]]
  - [[https://www.reddit.com/r/rollerblading/comments/7sceke/question_about_hydrogen_wheels/][Question about Hydrogen Wheels : rollerblading]]
  - [[https://www.reddit.com/r/rollerblading/comments/89a47p/hydrogen_wheels/][Hydrogen wheels? : rollerblading]]
  - [[https://www.reddit.com/r/rollerblading/comments/8w3w56/undercover_mushroom_blading_wheels_or_hydrogen/][Undercover Mushroom Blading wheels or Hydrogen (100mm)? : rollerblading]]
  - [[https://www.reddit.com/r/rollerblading/comments/3h6nwf/recs_for_80mm_wheels_to_practice_slides/][Recs for 80mm wheels to practice slides? : rollerblading]]
  - [[https://www.reddit.com/r/rollerblading/comments/8176l7/anyone_tried_both_undercover_mushroom_blading/][anyone tried both undercover mushroom blading 100mm wheel and rollerblade hydrogen 100mm wheel? Any feedback : rollerblading]]
  - [[https://www.reddit.com/r/rollerblading/comments/6y5dvi/what_wheels_are_the_best_for_urban_scene/][What wheels are the best for urban scene? : rollerblading]]

** Bearings

 [[https://www.proskatersplace.com/shop/inline-skates/inline-skate-bearings/rustproof-storm-16pk/][Seba Storm Twincam Rustproof]]

- Slow bearings are no fun. Cleaning/re-lubing bearings is no fun, especially if you have to do it often/every time your skates get a little wet. The solution? Fast weatherproof bearings.
- I have the Seba Storm Twincam Rustproof bearings in my Wizard skates, and Leon Basin of Shop Task highly recommends them. Based on the last conversation we had, he said that they were the longest-lasting, maintenance-free bearings he had used.

** Natural rocker

It would preferable to have the frames have a natural rocker built in like the Wizard frames. However, the wheels will eventually wear into a natural rocker assuming proper rotation, so it isn't the end of the world that it's not built into the frame. Having it built into the 4x80 skates is less important than having it built into the 4x110 skates, which are very hard to maneuver without it. 4x80 flat is still reasonably maneuverable, and since the wheelbase is short, crossovers are easy/fast and add quite a bit in the maneuverability department.

All this to say, it would be ideal and desirable to have the natural rocker built in so that you get it from day one rather than having to wear wheels into it, but it's not that big a deal for 4x80 skates, especially compared to its importance for 4x110 skates.

* Carbon skates, Intuition liners, and swappable frames

** Razors Cosmo skates?

There was a period of time after I came across the [[https://www.inlinewarehouse.com/Razors_Cosmo_Skates/descpage-10RCS.html][Razors Cosmo skates]] with [[https://www.youtube.com/watch?v=TQBLkHXHUWM][swappable frames]] that I thought I would build a whole bunch of skate configurations around a single boot/liner combination. There is certainly an attractiveness to being able to carry several frame combinations with you in a backpack rather than lugging several complete sets of skates around. Additionally, buying one boot/liner is a lot cheaper. However, I ultimately decided against going this route. Here's why:

- Upon talking with Leon Basin of Shop Task, he told me that much of the feedback from experienced skaters in relation to these was somewhat lukewarm. The concept was cool, in other words, but he cautioned me against getting too enamored. While Leon's friends are probably a heck of a lot harder on skates than the rest of us, there are evidently reports of the frame system popping off. You can of course bolt the swappable soul-frames on to the boot, but then there's not much point to buying multiple soul-frames (unbolting a soul-frame vs unbolting a frame with wheels is not much different).
- Leon was very professional the whole time -- he never said bad things about the company or made sweeping generalizations. He was also up front about the fact that he had never personally tried the skates, just heard things about them. The biggest takeaway was that he was not sure if this system would be up to the forces generated by big-wheels, marketing aside. There's a reason why a lot people regularly using 4x110 or 3x125 end up in carbon boots like the Seba SX, Seba Igor, Flying Eagle Drift, Powerslide Hardcore Evo, etc.: you really do need a stiff boot for good responsiveness and power transfer.
- When I thought about one of the reasons why I was interest in swappable frames -- being able to take multiple pairs of skates with me when I travel -- I realized that while it sounds great in theory to be able to have a 4x110 or 3x125 frame, freeskate 4x80 frame, aggressive frame, and slalom 4x80 frame, I'd only ever really use the big-wheel frame and freeskate frame. If I'm in a new place, I want to explore, not set up cones in a park or hit some vert.
  - I've spent a lot of time trying to figure out what it is I want to get out of skating, and I've narrowed it down to 4 categories: speed/commuting/fitness (4x110 Wizard skates), spirited urban freeskating (4x80 naturally rockered), aggressive (4x60 flat), and slalom/artistic (4x80 banana rockered). There are other categories out there (downhill and freestyle sliding, for example), but these are the four that I decided I'm interested in.
  - Slalom/artistic and aggressive are to spice things up for variety. When I'm at home, I will have skated most of the parks/trails/etc. near me multiple times, so general fitness skating and spirited urban skating are relatively less sparkly and exciting than when in new cities and environments. Under these circumstances, the variety makes sense. But if you give me the choice of exploring new places on skates or doing slalom/aggressive, I'll pick exploring every time.
  - Flying with two pairs of skates may seem like crazy out-there if you're not some touring pro or whatever, but hey, exercise is important, right? (I'm also in the process of devising a travel-ready collection of bodyweight equipment like a [[https://www.pullup-dip.com/portable-pull-up-bar][pullup/dip bar]] and [[https://www.amazon.com/gp/product/B008DNAJ5M/][rotating stands for pushups]]). I'm a pretty minimalistic person and really into well-designed travel clothing, so dedicating a checked-bag to workout stuff doesn't seem so radical to me. Only for longer trips of course... and since I'm still in college all of this is hypothetical.
- You know what's even faster than swapping out frames in a minute? Not having to swap out frames at all by having 4 separate pairs of skates, skates that don't have extra unnecessary hardware related to swapping out frames!
- Finally, while initially I thought that there was not too much difference between different boot and liner combinations, now I'm pretty sure that trying to force all disciplines of skating into the same boot is fairly suboptimal. See below.

** The liner/boot table

Today I had an epiphany of sorts. I had been turning over in my head the seeming incongruity in the fact that all 4x80 freeskates use plastic boots while lots of people on Reddit (etc.) swear by carbon boots for increased responsiveness and control. I don't know why it took me so long to realize this but guess what: the people using freeskates and the people arguing for carbon boots are not always intersecting sets.

Similarly, I was pondering why so many people use Intuition liners (Leon Basin and Shaun Unwin of Shop Task, Minh, several very helpful Reddit people I've talked to), yet so many skates have integrated liners or liners that use foam that compresses more (i.e., foam that absorbs more energy). The Intuition liners give exceptional responsivness and power transfer. Who wouldn't want that.... right? Were all these companies cutting corners or just dumb or something? It didn't seem likely, but I couldn't figure it out.

Behold, the tabular answer to my questions:

|                              | *Carbon boot*           | *Plastic boot*          |
| *Stiff liner like Intuition* | Speed/commuting/fitness | Doesn't make sense      |
| *Squishier liner*            | Doesn't make sense      | Freeskating, aggressive |
| *Minimal liner*              | Slalom/artistic         | Doesn't make sense      |

Let's break it down:

- When you have a stiff carbon boot and stiff liner, you end up with great responsiveness and power transfer combined with good comfort. This is ideal for skating fast while commuting or for exercise. (You could skate slow for exercise but that's boring, so I basically consider "long distance non-competitive speed skating" and "fitness skating" synonymous -- at least for myself).
- When you have a plastic boot and squishier liner, you have somewhat muted responsiveness and worse power transfer, but much better shock absorption. Think about it: power transfer cuts both ways. Better power transfer means more energy gets transferred from your legs to the ground when you push off in a stride, but also means that more energy gets transferred from the ground to your legs when stair bashing and landing jumps. For skating focused on going fast, power transfer is good (see above); for urban freeskating where you are jumping on everything, landing big gaps, bashing a bunch of stairs, and happily doing tricks on obstacles in the city, power transfer is actually bad, since all the energy from landing things will go straight into your legs/joints. Speed is not the bottleneck in this sort of skating: 4x80 skates will go plenty fast enough for urban freeskating (perhaps even fast enough for speed wobbles to become a problem) without carbon boots. Rather, it makes sense to design skates for this purpose  around impact forces.
- Aggressive is basically the same. Landing gaps and jumping on and off of stuff to grind is going to be more pleasant if you have "worse" power transfer, meaning that your boots and liners absorb more energy. There is the caveat here that you do want your boots relatively responsive so that you can "feel" where your boots are when grinding: there is a balance that must be struck.
- Finally, slalom/artistic skating can get away with really stiff carbon boots with minimal lining since they are designed for the absolute maximum responsiveness and control without needing to worry about large forces from big wheels and skating fast comfortably for long distances. Thus, while Intuition liners make sense for big wheel skates like the Wizards, they aren't actually needed for slalom/artistic skating, and add unnecessary bulk/weight.
  - It's worth pointing out that one thing the Intuition liners do incontrovertibly give is a perfect fit once broken in. If you can't heat mold your fancy carbon slalom skates, then the comfort in the skates may not be sufficient enough to skate without something like Intuition liners. Fortunately, you /can/ heat mold many high-end carbon slalom skates from various manufacturers, so the points above stand.
- Finally, all the other combinations simply don't make sense. Combining a stiff carbon boot with a squishy liner or a plastic boot with a stiff liner mixes optimization priorities: these combinations don't focus on either power transfer/responsiveness or shock absorption, and therefore, I don't see a use for them. While I guess plastic boots with minimal lining would work OK for slalom, carbon is simply better in the responsiveness department, which is what slalom is all about. I'm actually not aware of any plastic boots with built-in liners (most have removable liners), but that is the category that is being discussed in the abstract.

There are a couple other things to take into account when selecting skates, which I'll discuss below.

** Frame material/attachment

Aggressive skates will use plastic frames for grinding, and therefore it makes sense to integrate the frames into the boot to recess the wheels as much as possible (see the USD Aeon skates -- I'm planning on using the [[http://usd-skate.com/projects/aeon-60-black/][60mm skate]] once I get into aggressive). The [[http://www.oysius.com/][Oysi frame]] is an example of a UFS frame that accomplishes something similar via soul-plate modification. (Although I don't think it is as low as the USD Aeon 72's, it probably has a better grinding space). According to Leon, the Oysi frames are really popular among experienced skaters, and a good choice to ride flat when doing aggressive.

All other skates (even urban freeskates that might benefit from more shock absorption) should use stiff aluminum frames for power transfer: plastic frames are quite inefficient.

In terms of attachment, aside from the unibody Aeon skates, all other skates use bolts to attach the frames. While I'm sure some of Powerslide's marketing regarding their Trinity frame mounting system is somewhat overstated, having multiple attachment points really does make gobs of sense (lowering overall frame height, increasing control, decreasing vibrations, etc.). Of course, hockey skates did this first: most hockey frames have four points of attachment.

Failing this, UFS makes more sense than 165 or 195 mounting, in my opinion. 165 and 195 are unnecessarily tall, while UFS is flat.

Finally, having the option to shift the frame front-to-back (for adjusting where the wheelbase lies under your foot) and side-to-side (for correcting pronation/supination) is quite beneficial. This is one of the only areas in which the Seba SX/Wizard frame combination is lacking, since you cannot adjust how the frames are mounted at all.

** Heel raise

Skating forwards benefits from having a slight frontwards tilt: it is beneficial for skates to naturally tip the skater forward a little bit. Inline hockey players typically have a much more exaggerated forward tilt since they sprint from a stop so often (and the tilt gives them more leverage when doing this), but for general skating, only a little bit is desirable in my opinion -- just enough to get a skater's center of mass more forward and low with relaxed leg positioning. Some skaters advocate for more of a tilt (Bill Stoppard, e.g., personally uses a Hi-Lo wheel configuration) since their skating utilizes more sprints. Use case is everything.

Well designed skates often have this forward tilt built in. The Wizard frames, for example, even though they are mounted on flat UFS boots, have a built in forward tilt for all the reasons above. Letting wheels wear into a natural rocker by doing a 1-1, 2-2, etc. rotation will also develop this forward tilt naturally if you start on a flat setup.

Now, slalom/artistic skates benefit from having a more pronounced tilt (a ~5mm heel raise is probably a good idea). This is because more skating in these disciplines is done on the toes, perhaps even on the first wheel alone. Having a bigger tilt built in means that it is less difficult for a skater to shift their weight onto their toes for maneuvers, and less tiring to hold such positions over time.

* Conclusions

Ok, so this post got away from me a little bit. The main takeaway was going to be essentially that buying a 4x80 skate makes sense for me for learning purposes and urban skating thereafter (coexisting with my Wizard frames), but I got a little off topic talking about selection criteria and whatnot. Oh well.

Based on the above reasoning (and other accumulated wisdom from research I've done/conversations I've had with Leon), here are all the configurations that I think are optimal given my interests. These may change over time if I update my thinking, but I don't think you could go wrong with the below:

| Skating Discipline      | Boot                        | Liner                               | Frame                                             | Wheels                        | Bearings                     |
|-------------------------+-----------------------------+-------------------------------------+---------------------------------------------------+-------------------------------+------------------------------|
| Speed/commuting/fitness | Seba SX                     | Intuition Skate Liner V2            | Wizard NR110's (NR100's if you have smaller feet) | UC 110mm 86a (bullet profile) | Seba Storm Twincam Rustprrof |
| Urban freeskating       | Powerslide Next             | The stock MyFit semi-squishy liners | Flat 4x80 Trinity frame                           | UC 80mm 86a (bullet profile)  | Seba Storm Twincam Rustproof |
| Aggressive              | USD Aeon 60mm               | The stock MyFit semi-squishy liners | N/A (integrated with boot)                        | UC 60mm 90a (bullet profile)  | Seba Storm Twincam Rustproof |
| Slalom/artistic         | Powerslide Hardcore Evo Pro | Built-in, heat-moldable liner       | Pre-rockered 4x80 Trinity frame                 | UC 80mm 86a (bullet profile)  | Seba Storm Twincam Rustproof |

I own the speed configuration (except have Seba CC 84a wheels instead of the Undercover 110mm 86a wheels -- Leon likes the smaller core/additional urethane on the 110mm Seba wheels), and am in the process of ordering the freeskating configuration. I'm going to hold off on buying any more equipment until I'm a much better skater in general, since slalom and aggressive both seem to me to be more advanced and specialized.

Some people might want to swap out the Wizard frames (speed/commuting/fitness skates for me) with 3x110 or 3x125 skates. They're certainly cheaper. I've had Leon explain the Wizard frames to me several times now, and I really do think they make a lot of sense, combining ridiculous stability with good maneuverability. They are, however, extremely heavy, and do make crossovers difficult (and this is coming from someone who is 6' 5"). To me, the relaxed skating position that the long, stable frames afford is worth the weight (which also helps keep the frames tame at very high speeds due to momentum), but I certainly understand why some people might instead favor more nimble triskates, skates with low weight that are really swivelly due to a middle-wheel pivot. To use a motorcycle analogy, Wizard skates are like the stable, powerful touring bikes (think BMW R1200GS), and 3x110/3x125 are like the ridiculously fast, ridiculously nimble supersport bikes (think Kawasaki Ninja ZX-10RR). You might arguably get more enjoyment out of the latter, but with great power comes great responsibility. I'd rather be in meditation-zen-flow-mode than faceplant every time my balance gets a little off, but maybe that's just me. Different strokes for different folks.

Of course, you should take everything I say here with a monumental helping of salt, since I'm still basically a skating neophyte. But hey, even new people have opinions.
