---
title: "Having a Website and Complications Therein"
description: ""
date: 2018-01-20T14:27:34-04:00
categories: ["Processes"]
tags: ["web design"]
---

A question I have gotten from several people in the few months I've had my site up is "what's the point?" It's a good question.

** Bad Reasons To Have a Website

First, some reasons I think are lame. A lot of people recommend you have a website to showcase your CV/Resume, your projects, and "what skills and experience you bring to the table." (You know the type of arguments, and the nauseating language employed therein).

To be perfectly honest, this is exactly the sort of corporate standardization and conformity that drives me nuts. In other words, this is /exactly the opposite of a good reason/ for having your own website. Anyone who has been around me in real life knows that marketing and public relations are two of the things in life that make me legitimately wrathful. You can couch them in terms of "communicating the benefits of your product," "customer management," etc., but when it comes down to it, the disciplines teach you how to spin blatant lies and nonsense. They are mediums of unethical manipulation of vulnerable people that aren't aware of the bias in presentation, either due to systemic enforcement of ignorance by companies, the government, and so forth for selfish gain, or simply because they have never had the corruption of the system exposed to them in a stark, no-holds-barred, manner. See [[https://steventammen.com/reading-list/#escaping-the-cave][here]] for some recommended reading on the subject.

All this to say, I think it is a very bad idea to create a website and publish content solely to make yourself appear like a qualified, interesting person. That's falseness and insincerity, and if you do it, shame on you. With as little truth as there is in how we interact with each other nowadays, making up stuff to sound intelligent is all the more despicable. Particularly if it leads to you getting a job/promotion over a more qualified person who was unwilling to "play the game" of truth twisting and self-aggrandizement.

Now, with that big one out of the way, here's a few other things to avoid:

- Hosting a website/writing to preach your views to others as holy dogma that must not be questioned.
- Hosting a website/writing to stir up resentment between groups of people (think politically, racially, etc.). In other words, demagoguery.
- Hosting a website/writing to insult, vilify, or harm any group of people, even if they are morally backwards and might kind of deserve it. Hate begets hate, not progress.
- Hosting a website/writing to troll others. Trolling is fun but not constructive.

I could go on, but you get the idea. Don't be evil/insensitive/rude. The prohibition against trolling bears repeating. It is satisfying to get people worked up without them knowing you are not serious, but it is more satisfying to help them see the truth of the matters that they are irrationally emotional about. (Taking pains to not become a white knight in so doing).

** Good Reasons To Have a Website

I found a quote that almost perfectly encapsulates my main reason for having a website. From the middle of [[http://paulgraham.com/hundred.html][this excellent piece]]:

#+BEGIN_QUOTE
  The word "essay" comes from the French verb "essayer", which means "to try". An essay, in the original sense, is something you write to try to figure something out. This happens in software too. I think some of the best programs were essays, in the sense that the authors didn't know when they started exactly what they were trying to write.
#+END_QUOTE

In other words, I write for me. It's selfish. Getting everything "on paper" so that I can more clearly see relationships in information and reason about it helps me figure stuff out. Even if I weren't publishing things on the internet, I'd still do more or less do what I do, since it's how progress in thought is attained.

But there's benefit to publishing these "essays," these stabs at the truth. What are they, you ask? Well there are several:

- I'm kinda dumb sometimes. Other people are kinda smart sometimes. The synthesis of these means that I can learn a lot from what other people say/think about what I write.

  - This is basically what the open source movement is all about: multiple people lead to higher quality projects since sometimes we all make mistakes and benefit from others' perspectives.

- [[http://www.catb.org/~esr/faqs/hacker-howto.html#believe2][No problem should ever have to be solved twice]]. (You should really read that all the way through. It's absolutely fantastic). Sharing knowledge is important.
- "Putting it out there" makes me take things more seriously because people can fact check me and contradict me if I'm wrong. Humans have a nasty habit of rationalizing their actions and committing intellectual suicide-by-self-justification. If I commit such sins when I lock up my writing in a journal, I'll never know. If I commit such sins when I publish something, someone is bound to tell me, either nicely and constructively, or gloatingly and rudely. Either way, I'll know that I messed up somewhere, and won't get trapped by self-delusion.

** Hypocrisy

An astute observer might note that I have actually published my CV/Resume on my website, and do mention my side projects in what I write. What gives then? I thought websites were to put your thoughts out there to make them better? How does posting such things help?

You see, the thing is, I'm not against resumes, or portfolios, or other things of the sort. I'm against websites existing simply because people want to paint themselves as more educated or qualified than they really are. That is, I'm against these things serving as a marketing medium, not the things themselves.

Here's how I view it: an ethically constructed resume or CV accurately records skills, experiences and qualifications for an individual without embellishing or misrepresenting. It is concise, factual, and descriptive. It is not vague and does not promise more than what is there. A person should be prepared to defend the exact wording of every phrase included in the document without qualification.

The same thing would go for the now-ubiquitous "elevator pitch." It is a decidedly good thing to be able to briefly summarize why you are an attractive value proposition -- to objectively lay out what things you bring to the table. But there should not be rhetoric or showboating or anything like that in this. It should be kept matter-of-fact. And people who lie or misrepresent themselves in any part of the job-seeking process should be punished swiftly and severely.

** On Naming Websites

Having an uncommon enough last name let me obtain firstlast.com, which I think is ideal. Several people have told me that they think it is really pretentious to have a website named after myself, but I would contend that that is simply a bias people hold because of all the stupid self-promoting websites scorned above.

The thing common to this website is me. I don't have any one particular interest, so a website named after any one of them singularly (e.g., efficient-text-entry.com) would prove to be misleading in many circumstances. An arbitrary name works fine for large companies (e.g., Amazon) or specific projects (e.g., [[https://web.hypothes.is/][hypothes.is]]), but doesn't make a lot of sense for individuals.

If you make a habit of tooting your own horn in everything you write then that is obnoxious and you should stop. But I'm not going to change my website name to something unrelated to my personal name (or feel bad about setting things up this way) since I am the thing that most clearly ties all the content together on this site: these are /my/ thoughts.

** On Anonymity

Some people also argue for writing anonymously. I'm not one of them. If you don't have the guts to put your name behind what you are writing, then you probably shouldn't be writing it. Getting "doxxed" is only a problem if you aren't enough of a man (or woman) to associate your name with your views.

Letting people know who you really are is actually something /in support of/ posting a CV/Resume, portfolio, etc. I use heuristics a lot to decide who I should even contemplate listening to, and to me, not knowing the real author of something is more of a red flag than learning that the author had 2.7 GPA and and dropped out of college.

Why? Because, for example, people drop out of college for all kinds of reasons. They get fed up with the political correctness and mysterious expense categories they have no control over. They get sick of watching how the University pats itself on the back for its students' successes when usually said students succeeded almost entirely on their own drive and determination, sometimes despite the University.

Now don't get me wrong. The brokenness of higher education does not equate into a blanket condemnation of the system. (This is ultimately a topic for a separate post). What I was getting at is that people and circumstances are complicated, and I at least won't arbitrarily judge them without hearing their take on their path. But people who won't give any information about themselves? My first instinct (verified through experience over time) is to think that they're hiding something.
