---
title: "Skating Environments"
description: ""
date: 2018-05-14T17:04:33-04:00
categories: ["Immaterial Things"]
tags: ["skating", "commuting", "safety"]
---

** Identifying what kind of skating you want to do

Obviously if you are doing aggressive skating, you are going to want rails and ledges to grind and things to jump onto and off of. If you are doing slalom, you are going to want a large flat surface where you can set up cones and not bother people unduly. If you are doing speed skating, you are going to want a route that lets you avoid anything that could upset your stride, since speed skates are pretty terrible at maneuvering should anything come up. (In other words, you are going to want a very controlled route, like a track or straight empty road, where you won't face consequences due to a long wheelbase and lack of ankle support).

However, what I am interested in more than these is the best type of environment for general skating: cruising along, perhaps going backwards here and there, bombing hills as they come up, carving back and forth as a mood takes you, jumping curbs and objects for fun -- even hopping up on ledges and perhaps skating down stairs, and so forth. Since this is the sort of skating I want to do (sometimes called "urban freeride" or something of the sort), this is the sort of environment I will be examining in this post.

** What sot of metrics can we use to evaluate environments?

Whenever you compare two things, you need to have metrics that you can use to evaluate them. How are you going to know if something is better or worse than something else if you have no way of benchmarking them?

For this reason I have attempted to come up with some areas in which we might compare skating environments for general skating:

- physical safety of the environment
- crowdedness of the environment
- variety in the environment
- beauty and ambiance of the environment

I have put these in their order of importance, as it seems to me.

*** Physical safety of the environment

This would be the most important factor, in my opinion. If the roads themselves are not safe, then they are poor choice for a skating environment right off the bat. Here's some questions you should ask yourself when attempting to evaluate the physical safety of an environment:

1. Are the roads and paths relatively smooth, or are there lots of imperfections and potholes everywhere? (Note: rough surfaces are OK as long your wheels are big enough, it's the dangerous sort of imperfections that this is talking about: holes and cracks that could cause you to fall).
2. Is there loose debris on the road (like gravel, sticks, or trash) that could pose a safety risk?
3. Is there surface concealment (like leaves or discarded newspapers) that obscures your view of the road surface, perhaps covering up safety risks?
4. Are there potential sources of liquid threats, like pooled oil or even just water from a leaky hydrant or somebody watering their lawn? (Liquids, particularly oil-based liquids, reduce friction and can cause you to lose control).
5. Are there lots of traffic markings (turn arrows in particular are nasty) that have a low coefficient of friction and might cause you to slide?
6. Is there sufficient space for you to maneuver in the greater part of your skating? (Brief periods of less space are OK -- statistically, you want wider spaces "most of the time" to reduce your risk envelope).
7. Is the road/path "predictable"? Roads with lanes that end suddenly, lots of blind corners, and so forth are not predictable.
8. Are there visual obstructions like trees and bushes that block your view of side-streets or merging lanes?
9. If skating at night, is the road/path well-lit?

I could probably come up with others questions if I tried. But this is a good start. The idea is to choose a physical skating environment that is inherently safer from the get go. Unless you have some compelling reason to choose an environment that is unsafe to skate in (see commuting, below), you should endeavor to never skate in environments that are inherently unsafe.

*** Crowdedness of the environment

By "crowdedness," I mean the extent to which you have to share the environment with other moving things.

There are several categories of other moving things you may have to deal with. Some are definitely more important than others, and I've arranged them in descending order of importance, according to my take on the situation:

**** 1. Cars and other motor vehicles like motorycles or mopeds

Motor vehicles are much heavier than you are, and will always "win" in any sort of collision. For this reason, they pose the greatest risk to you in a physical sense. There is also the fact that many drivers are incompetent and/or engage in reckless behavior with little or no concern for the safety of those around them, and the fact that motor vehicles travel very fast, giving you little reaction time. So putting these things together, motor vehicles are your sworn enemies when skating. Just like competent motorcyclists view all drivers ("cagers" -- people who drive around in two-ton metal cages) as out to kill them, so too should skaters treat all operators of motor vehicles as essentially malevolent. As a rule of thumb, acting as if all motor vehicles are potential assassins will make you skate with a greater appreciation for the real risk they pose to you.

**** 2. Other people using personal transport: bikers, longboarders, other skaters, etc.

While other people using personal transport are less dangerous to you than cars in a physical sense (they are less massive so carry with them less potential for harm), they are still moving at high(er) speeds, and therefore pose a more significant threat than slower moving things. Their speed makes them dangerous just how motor vehicles' speed made them dangerous: you have less time to react to fast moving objects than slow moving objects. Many of these people (particularly bikers) will still have greater mass and probably greater speed than you as well, meaning that you still "lose" in collisions.

However, most of these folks will be more in tune with the concepts of sharing the road and peaceful coexistence than drivers. This doesn't mean that you should treat them as non-threatening, but does mean that you can probably expect them to do slightly less boneheaded things around you.

**** 3. Children and dogs

We are now into the range of moving things where you will "win" in a collision. I count children and dogs as more dangerous than adults (even though adults are bigger and have more mass) mostly because they are significantly more unpredictable than adults that are paying attention.

Most of the time dealing with children and dogs that get in your way will involve evasive actions like swerving out of the way. The fun comes when you combine these threats with the others above: a kid runs out in front of you, but you have a biker behind you and a car to your left. What do you do?

Aggressive dogs can be a big problem if they follow you. Carrying pepper spray is not a bad idea to deal with persistent dog threats, but it is best to not ever have to worry about them. This means you should endeavor to either avoid yards with aggressive dogs or get leash laws etc. enforced if you can't avoid them (like if the yard with an aggressive dog happens to be your neighbor's).

**** 4. Adult pedestrians

If pedestrians stay where they are supposed to and pay attention, they usually don't pose too much of a threat. The problem is, very few stay where they are supposed to and pay attention.

Jaywalking is common in many places, and, astounding as it is, some people won't look before crossing the street. Many people will also have headphones in and have their eyes glued to their phones, making them much less observant of their surroundings. Unless you see eyeballs up and aware, and a distinct lack of headphones, you should probably assume that pedestrians are unaware of your presence.

If you are on paved trails in parks (rather than on sidewalks), you probably have to worry less. Pedestrians on such trails will be more used to skaters, since paved park trails are popular for fitness skaters, skateboarders, etc. But the less of them the better still.

Sidewalks with people walking in multiple directions are especially bad, and you should basically strive to avoid skating on crowded sidewalks if at all possible. If the pedestrian density is enough that you don't have very much room, you will be forced to go slowly and be cautious, since you never know if someone might do something stupid and put you at risk.

**** What all this means

When evaluating skating environments, those with less motor vehicles, less people on personal transportation, less children and dogs, and less pedestrians are superior choices.

Unlike safe physical environments (which do actually exist), you will generally not be able to find a place free from all of the above. This means you should prioritize skating environments that are the least crowded, and have the smallest proportion of "big threats" (motor vehicles in particular). This makes quiet residential streets and park trails good choices, and main city streets (with chaotic traffic, crowded bike lanes, and lots of pedestrians on sidewalks) just about as bad as could be.

*** Variety in the environment

One of the things that draws me to skating over things like cycling is that you can do a whole bunch of things with it. Getting bored of going forwards? Try going backwards. Getting bored of that? Try carving down a hill. That too? Try jumping over obstacles as you encounter them.

Some skating variety can be introduced by simply switching up how you skate. But some of it depends on what sort of things are present in the environment you are skating in. If your environment is an outdoor quarter-mile track, then you don't have very much variety in environment. Everything will look the same every lap, and you won't find new curbs to hop, hills to bomb, or quiet streets to examine.

I never make an effort to select environments that have a super wide spread of features, because you will encounter new things so long as you keep moving around. The problem is when literally everything looks and functions the same in a large geographical area: then you get no variety.

In general, I have found city streets in "downtown areas" to be rather boring because they are all basically alike (congested traffic, a bike lane if you're lucky, and crowded sidewalks), and so too with tracks and shorter jogging trails that lack variety.

My favorite spots in this regard are lower-traffic city/residential street networks, business and campus locations after hours, and longer park trails where there is more variety. By skating along you'll encounter different environment features that let you do different things (e.g., maybe a sloped embankment to roll up and down, some ledges to skate on, a set of stairs, some curbs to hop, etc.). Variety in environment lets you switch up your skating to a higher degree and express more creativity than if you skate the same thing over and over again.

Note: in my opinion, you don't have to take this so far as to say that you always have be skating things you haven't seen before. That is ridiculous. Rather, the notion is that instead of skating around the same block over and over again, you branch out and explore the environments around you. By doing so you will naturally encounter new terrain that lets you constantly being doing different things with your skating.

***  Beauty and ambiance of the environment

Would you rather skate through a wooded forest with birds chirping, sunlight filtering through the trees, and a pleasant, earthy smell... or the noisy din of a city street, with trash and dirty buildings as your visual surroundings, and car exhaust as your olfactory experience? I don't know about you, but this one is easy for me.

In general, I like roads and trails with more nature and less civilization. However, I'm also OK with developed areas as long as they are aesthetically pleasing and clean/unpolluted. Grassy vistas with fountains; cool sculptures and bushes; glass and metal conference centers -- these are all fine by me. In Georgia where I am at the moment, I actually find that neighborhood streets tend to have a lot of trees, bushes and flowers, so that I don't even have to go to a park to get a good fill of nature.

This is an area where you should focus your selections if you have the option. I wouldn't ever skate on a physically unsafe or extremely crowded road just because it was pretty, and I would still try not to skate on a really pretty road if there was never any variation whatsoever. But since there will usually be some variation, usually it is just a matter of making sure a pretty road is safe and there aren't that many other people on it.

** How can these variables inform what sort of environments we select?

For some things, decisions on where to skate and where not to skate are pretty clear cut. If the road is physically unsafe (e.g., huge potholes everywhere), you just shouldn't skate it period. If the road/bike path/sidewalk attached to the road is really crowded with cars, bikers, and pedestrians, it would probably be wise to steer clear if you can help it. But sometimes there are "in-between" situations that call for a bit more thought. I've listed out some of the common ones from my experience below.

*** Mostly uncrowded sidewalks and park trails

This may be the most common situation that requires thought. In parks especially, you will rarely ever be the only person on a trail. So the question becomes how many other people need to be on the trail before it becomes a poor skating environment? How about sidewalks?

This is something that I think will mostly come down to how many blind corners there are, and how steep things are. If the trail is relatively flat and you can always look 8-12 seconds ahead, then as long as the trail/sidewalk is not super crowded, you should be able to skate on it (even at higher speeds) without incident. (So long as you are looking out for children and dogs). If you have good visibility and there is a big downhill, you can still skate it, but you will just have to pay extra attention to modulating your speed so that you don't present a risk to others on the trail.

In my opinion, the upper bound on human density is if you cannot get at least one decent stride in between encountering other people. If you get much past this point, you will not be able to safely skate at speed since you have no way of actually dodging around people if stuff comes up. In other words, you wont have a sufficient amount of maneuvering room to make higher speeds safe.

*** Less major roads with some cars and a speed limit around 25 to 35 mph

In my opinion, situations like this mostly come down to whether "some cars" can be termed traffic proper, or simply a car every now and then. If you are on the road and there is not traffic proper, people can just pass you without event (assuming it is legal to do so). However, if there is traffic going both ways (or in multiple lanes going the same way, depending), and cars cannot move around you, then you probably shouldn't be skating on the road since you are acting as a traffic risk.

*** Bike paths

Bike paths can be kind of iffy sometimes. Many of them are not very wide, and don't really give you enough room to stride effectively. But at the same time, as long as you are not obstructing anyone else, it doesn't really matter if you can't get a full stride in.

My rule of thumb is that if the bike path actually gets used by bikers a lot, I'll typically try to avoid it so that I don't get in their way. But if it doesn't seem to get used that much, then I'll happily skate it, particularly if the road is quiet enough that I can skate into the rightmost lane most of the time and only stay fully in the bike lane when getting passed

Since I currently have plenty of full-width roads and trails around me, I find that I don't need to think about this too much. I just make use of the superior options. But I reckon this might be more of a factor for people in cities proper.

*** A mix of a busyish road and busyish sidewalk along the road

This is one of the tossups. If you can easily transition from street to sidewalk and vice versa you might be able to skate this comfortably, going into to the street to avoid sidewalk congestion and going onto the sidewalk to avoid street congestion. But you might hit circumstances where this doesn't work, or where you could previously go from one to the other but the environment changes and now you can't.

I would generally caution against situations like this unless you know the road and the area well and can anticipate where problems might come up.

** Are there any environments you should just always avoid?

Aside from the obvious ones, I personally do not think it is ever a good idea to skate in the busy part of a big city like New York. Other people (e.g., Casey Neistat of NY and Bill Stoppard of Toronto -- both on YouTube) certainly commute in the city with personal transportation, but I'm not convinced the benefits are worth the risks involved.

City commuting in general flunks all of the metrics for good skating environments. You usually can't choose your commuting path to such a degree that you can entirely avoid debris (e.g., sidewalk and street trash) and poor roads (which abound in cities, ironically). Most roads that you would need to go on for a city commute are a chaotic blend of pseudo-gridlocked traffic, bikes, impatient/preoccupied pedestrians, roadside merchants, delivery trucks, taxis... etc. The exact opposed of uncrowded. City streets also tend to have little variety, and mostly all look the same in a given area. And even if you might be able to pop a couple of tricks, all the traffic and people in the crowds above generally won't accommodate this behavior. Finally, most city commutes don't have the best scenery and ambiance (an understatement if there ever was one).

All of this means that I think skate commuting in the city is actually a rather bad idea. Assuming there is public transportation (which there is in most cities), I would rather avoid unnecessary risk by using that (particularly if it is subways rather than buses). Podcasts can make the time productive, and if you have the gear for it, you can even do some good work during this time.

You don't have to give skating up completely either. You can just choose to do it in better environments than what you might face on your commute. (If your commute itself is good, go for it).

** Anything else to think about?

Some skating environments may change over time. For example, if many leaves come down during fall, a road that was previously safe may become less safe due to the concealment from the leaves. Roads are going to be more unsafe right after storms when there is more debris. If there is construction going on somewhere, traffic patterns may change and cause a previously uncrowded road to become more crowded. And so forth.

But perhaps the largest and most important change variable is time of day. If you go skating at 5:00 in the morning, you are not going to have too much competition with other people. But if you try to go skating during rush hour (morning or evening), a road that is typically uncrowded may become crowded for some period of time. Taking this into account when you plan your skating sessions can make skating much more fun and enjoyable, particularly if you live in a higher-traffic place where it is harder to get roads to yourself.

** Are there any implications from all this?

If you presuppose a good skating environment (one that is physically safe, relatively uncrowded, has variety, and is hopefully nice to be in), you may make certain assumptions about the sorts of situations you will find yourself in. If you resolve right off the bat to not put yourself in heavy traffic and very crowded places, you don't need features that are related to these things.

This is most important when considering what sorts of skates to buy. Thinking about this question was the whole reason I went through the bother of making this post: could I actually choose environments that let me cross off some types of skates from my list of possibilities?

*** Electric skates

As discussed in my last post, [[https://www.steventammen.com/posts/electric-skates-vs-normal-inline-skates/]], electric skates have some distinct advantages:

- They allow skating without exertion.
- They allow faster speeds when confronting uphills of any gradient.
- They allow faster speeds in situations where there is very little side-to-side space.
- They allow braking requiring less precision.

But if you want to exercise and can assume skating environments where you will not pose a danger due to going slow up hills or be in danger from not being able to go fast in narrow spaces (and do not care about the extra time costs related to these things since you won't be commuting), then electric skates don't have any great advantages unless you are not capable of braking safely, or if you value the fun-factor of speed at all times (including going up hills) over exercise. Assuming that you will not be skating in traffic obviates many of the obvious advantages electric skates have, which means you can save ~$1000+ by noting that you do not need them in /your/ use case, and that they would just add extra weight and bulk. (Marketing aside).

*** Skates with smaller wheels and shorter frames

Resolving not to skate a lot in crowded places means you can value speed and stability over maneuverability to some extent, letting you pick skates with bigger wheels and a more comfortable, effortless ride. Bigger wheels are more efficient due to less inherent rolling resistance, and will enable higher speeds, in addition to being smoother in general. Greater stability lets you bomb hills more comfortably and worry less about your stance.

So it follows that if we can guarantee that the number of situations in which we need excessive maneuverability (as opposed to just "pretty good" maneuverability) will be few, we can safely opt for skates with bigger wheels and longer frames and get the benefits from doing so.











