---
title: "Clothing"
description: ""
date: 2018-03-18T17:49:13-04:00
categories: ["Material Things"]
tags: ["essential gear", "gear cluster", "clothing"]
inprogress: true
---

** Everyday Clothes

- [[https://www.railriders.com/men-versatac-light-shirt-p-1021.html?cPath=104_111][Shirt]]
- [[https://www.originalsoegear.com/collections/belts/products/cobra-riggers-belt-size-26-to-40-with-velcro-lining][Belt]]
- [[https://www.yathletics.com/products/silverair-merino-wool-boxer-brief][Underwear]]
- [[https://www.railriders.com/men-versatac-ultra-light-pants-p-994.html?cPath=104_110][Pants]]
- [[https://www.amazon.com/Vibram-Mens-KSO-Cross-Training/dp/B0108T2TT2][Vibram's KSO Evo]]
- [[http://us.vibram.com/shop/fivefingers/men/outdoor/trek-ascent-insulated/M53.html][Vibram's Trek Ascent Insulated]] (when it's too cold for the KSO's)

** Dressy Clothes

- [[https://woolandprince.com/collections/dress-shirts/products/dress-shirt-blue-stripe][Button-Down Shirt]]
- [[https://www.yathletics.com/products/silverair-merino-wool-boxer-brief][Underwear]] (same as above)
- [[https://www.outerboro.cc/collections/bundle-packs/products/motile-breeze-suit][Suit]]
- [[https://www.injinji.com/liner-crew-nuwool.html/][Toe Socks]]
- [[https://www.lemsshoes.com/shop/mens-nine2five-black.html][Dress Shoes]]

** Work Clothes

- Same shirt, belt, underwear and pants as everyday clothes
- [[https://www.injinji.com/liner-crew-nuwool.html/][Toe Socks]] (same as above)
- [[https://darntough.com/collections/mens-bike/products/breakaway-micro-crew-ultra-light][Second Sock Layer]] (worn to minimize rubbing)
- [[https://www.amazon.com/gp/product/B00AMLEPI0/][Work Boots]]

** Exercise Clothes

- [[http://www.qorkit.com/qor-16-5-lightweight-tee-dfd6bc.html][Short Sleeve Baselayer]]
- [[https://www.yathletics.com/products/silverair-merino-wool-boxer-brief][Underwear]] (same as above)
- [[https://www.amazon.com/Champion-Short-Pockets-Black-LARGE/dp/B000J9YQOS/][Cheap Synthetic Shorts]]
- [[https://www.amazon.com/Vibram-Mens-KSO-Cross-Training/dp/B0108T2TT2][Vibram's KSO Evo]] (same as above)

** In Colder Weather, Add

- [[http://www.qorkit.com/qor-16-5-lightweight-tee-dfd6bc.html][Short Sleeve Baselayer]]
- [[http://www.qorkit.com/qor-17-5-merino-crew-ls-c51b06.html][Long Sleeve Baselayer]]
- [[https://www.amazon.com/gp/product/B008LW6SW8/][Compression Calf Sleeves]]

** TODO: Other Section Ideas

- Reason for cobra rigger's belt vs. normal leather

  - Vastly superior in any emergency weight bearing situations, inside velcro can anchor multitool holder, doesn't wear out like many leather belts do.

- Reason for Crew vs. OTC socks vs. some other height

  - Best to have calf component separate so that it can work with VFFs or other shoes that one doesn't typically wear socks with. Therefore, lower socks.

- Even if other people's evaluations weren't a factor, would high-visibility shirt/pants be desirable for better safety?

  - No. While some of the reason these colors are so effective is their completely unnatural hue (which wouldn't go way with more people wearing them), we would not want to "dilute" the eye-catching effect by having everyone wear them. Imagine trying to spot a motorcyclist wearing a high-viz yellow vest if he was moving in front of a crowd of pedestrians on the sidewalk all wearing identical vests.
  - So these colors should be reserved for people that really benefit from wearing them.

- Color of pants, shirt, base layers (printing, shows wetness, heat from sun, hides stains).

  - If you concealed carry printing is more of a factor than for the rest of us. Darker colors don't print as much.
  - Lighter colors show wetness more.
  - Lighter colors reflect sunlight better and don't heat up as fast.
  - Most stains from everyday life (at least in my experience) are reddish or brownish: blood, ketchup, tomato sauce, chocolate, etc. Choosing a dark red or maroon color is a good way to handle these types of stains. (You should obviously try to wash out spills etc. as soon as possible).

    - Some people argue for white since it can be bleached if you stain it. The problem is that it shows stains so well that stains will be very visible until you do this. So unless you always carry around a spare shirt to change into, you'll have very unprofessional stains quite visible.

- How baggy should clothing be?

  - Tight clothing wicks moisture off the skin better.
  - Baggy clothing allows for more air-cooling via convection.
  - Tight clothing is bad if you're not in good shape -- if you gain weight, you may not want to or be able to wear it.
  - Baggy, untucked shirts make it much easier to conceal a firearm.

- Color of underwear? Socks?

  - Underwear should be some dark color that doesn't stain. (Nobody likes underwear stains). Black underwear does this best.
  - Socks should be a professional color to make them transferable across contexts. Dark grey is my preference (since it goes with both khaki and navy/black), but black is always safe too.

- Color: psychological factors (look more intelligent, etc.). Actual science behind this?

  - Need to do more research, but appears to be split. Some support for sports teams succeeding if they wear red.

- Is there any purpose to shirt collars?

  - If you need to hang something around your neck, particularly if it is a load of some kind, a collar can ensure no skin contact.
  - Collars also give more sun protection, especially if turned up.
  - Other than these things, not really.


