---
title: "Multitools"
description: ""
date: 2018-03-18T17:56:33-04:00
categories: ["Material Things"]
tags: ["essential gear", "edc"]
inprogress: true
---

** Discussed Models

LM = [[https://www.amazon.com/Leatherman-Charge-Multi-Tool-Stainless-Leather/dp/B019EN7RWC][Leatherman Charge TTI]] Vic = [[https://www.amazon.com/gp/product/B0002T5YNW/][Victorinox SwissTool Spirit]] [[https://www.amazon.com/Leatherman-831195-Squirt-Black-Keychain/dp/B0032Y2OT6/][Leatherman Squirt PS4]]

** LM Pros

- One-handed opening blades
- S30v steel
- True needle nose pliers that open wide
- A Diamond file that can be used to sharpen stuff and handle hard materials
- Wider opening scissors
- More sharply machined screwdrivers (that are much less likely to slip)
- Better wire cutters
- A pocket clip that is one of the best available on any pocket knife.

** LM Possible Improvements

- Make smaller tools accessible without opening
- Make bit drivers less stubby so that they could get into tighter places

** Vic Pros

- All tools accessible from outside
- All tools lock
- Pliers meet at tip, so that they are parallel when you grip rather than when they are closed (which doesn't make any sense)
- Handle design is very good for pliers ergonomically -- doesn't really inhibit use of other tools
- Rounded edges are comfortable to hold

** Vic Possible Improvements

- Move away from riveting everything together -- use something that can be loosened/tightened/taken apart/replaced
- Slightly narrower pliers
- Let pliers open a little wider
- Add a cutting hook
- Add a diamond coated file, medium grain on wood/metal side
- Improve grip of surface (not necessarily bead blasted --- because of corrosion factors --- but more grippable texture)
- Switch scissors around to be able to cut nails
- Make scissors openable to be able to sharpen
- One hand opening serrated knife, some way to get it open even when cold
- One hand opening for other large tools as well
- Add spring loaded pliers
- Add removable wire cutter inserts (that are able to be resharpened)
- Square off screwdrivers, use harder steel (that won't strip as easily)

** Multitools' Role in EDC

- Multitools fulfill all the main tool duties not covered by a plain edge knife (which is kept separate for a more ergonomic grip and greater controllability).
- A compact can be carried on the keychain and should contain all of your "essential" tool functions. It should also contained a smaller plain edge knife to use for specialized tasks for which a bigger blade would be undesirable (particularly if you have a larger utility blade like a PM2 or Mini-Griptilian). I always carry my compact, even when carrying a full size multitool and plain edge knife. This is because of the aforementioned smaller plain edge, and the fact that having duplicates of some of the essential tools can come in extremely handy sometimes (particularly pliers and drivers). Additionally, you may encounter some situations in which you can give your compact to a friend/colleague to effectively double the rate at which you do a job (like tightening screws, for example).
- A full size should carry all of the tools that you will actually have use for. It's best for your full size to have the essentials as well as your compact -- not for the purpose of gear "backups" (which are completely unecessary for EDC, statistically speaking -- survival is another matter), but because a full size will have beefier versions better suited for different tasks than the smaller compact versions. For example, I use the pliers, scissors, files, and bottle openers (vertical prying tools) on my full size and compact multitools in different ways -- so they are in no way "duplicate tools". (See above for duplicating drivers).
- Essential multitool tools, in my opinion (in no particular order)

  - Needlenose Pliers
  - Regular (i.e., Rounded) Pliers
  - Wirecutters
  - Knife (plain edge for compact, serrated blade for full size. Preferably full flat grind)
  - Scissors
  - Medium Flathead Driver
  - Medium Phillips Driver (can be 2D on compact multitools if necessary)
  - Wood/Metal File (preferably diamond coated)
  - Bottle opener (vertical prying tool)

- I would include an awl in this essential list, but almost all day-to-day awl tasks can be accomplished with a well-designed drop point knife tip (which is strong enough to take some torsional force without snapping). I don't usually need to make holes in harder materials like wood or tough plastic like ABS or PMMA (which would demand a real awl).
- Similarly, while I would include a wood/plastic saw in this essential list, most day-to-day saw tasks can be handled with kevlar cord used as a friction saw -- which can easily cut through plastic (e.g., PVC pipes) and many types of wood. The tasks that a kevlar friction saw can't handle are typically smaller, requiring finer control than possible with the friction saw, which requires two hands to use effectively. The smaller tasks can be completed with the toothed edge of a file (particularly if made out of a good tool steel or coated with diamond/carbide particles). Toothed file edges are much slower than wood saws at general cutting tasks because 1) their teeth are much less sharp than wood saw teeth, 2) their teeth get clogged much faster than wood saw teeth, 3) their teeth are much wider than wood saw teeth, and 4) the file faces provide cutting friction that smooth-faced wood saws do not have. However, toothed file edges work fine for small tasks, wherein the amount of material to cut is relatively low. Thus, the combination of kevlar friction saw + toothed file edge can handle most saw tasks, obviating the need for a dedicated saw if access to a full size multitool is restricted (due to knife restrictions, etc.). It is also worth pointing out that compact saws are inherently inefficient, making the kevlar friction saw option that much better under these circumstances.
- YMMV -- try to find a compact multitool with an awl and a saw if you really think you need them. These are the only other tools that I would consider putting in the essential category, as all the tools below are much more specialized, and used significantly less frequently. (Also worth mentioning: I consider a light horizontal prying tool essential as well, but a flathead driver always doubles as this, so I don't list it separately. It's best to have two different widths for prying -- like most SAKs and multitools do -- but this is not strictly essential, as a single width will get you ~80% of the way there).
- Other useful multitool tools, in my opinion (in no particular order)

  - Awl/Reamer
  - Wood/Plastic Saw (can handle drywall which a friction saw can't. Also deals with harder woods better)
  - Metal Saw
  - Larger/smaller Flathead sizes
  - Chisel
  - Can opener
  - Carrying Hook (for pulling twine, distributing load weight, etc.)
  - Cutting Hook (for cutting things without the fear of scoring them like you might wth a knife -- more important to have if you don't carry a small plain edge, but useful even if you do just to be sure)
  - Wire Stripping/Scraping Tool (See SwissTool Spirit)

- Some people think bit-drivers are the best thing since sliced bread, but for an EDC multitool, they don't make very much sense (since you only commonly need a medium phillips and small/medium/large flatheads). A socket/driver combination tool ([[https://www.amazon.com/gp/product/B00327HT5W/][example]]) makes way more sense.

** My Picks

- [[https://www.amazon.com/gp/product/B0002T5YNW/][Victorinox SwissTool Spirit]]
- [[https://www.amazon.com/Leatherman-831195-Squirt-Black-Keychain/dp/B0032Y2OT6/][Leatherman Squirt PS4]]
