---
title: "Watches"
description: ""
date: 2018-03-18T18:02:19-04:00
categories: ["Material Things"]
tags: ["essential gear", "edc"]
inprogress: true
---

** Watch Type

- Analog watches superior for telling relative time
- But digital watches have desirable features like stopwatches, timers, day/date, world time, alarms, etc.
- Therefore, analog-digital watches make sense

** Case

- Reasonably impact resistant, chemical resistant, magnetic resistant, temperature resistant, pressure resistant/water resistant. Balance good specs with price and use case.
- Make the lugs about as wide as the watch face (i.e., don't add width), the thicker the watch band material, the more it distributes pressure on the wrist. However, bigger (nylon or leather) bands also dry slower, and bigger lugs are heavier. Balance (e.g., 20mm) probably best.
- Lugs should be slightly curved, an ideal shape to fit different wrist sizes (some flatter, rounder, etc.). Should not stick out so far as to be uncomfortable.
- No unecessary edges or bulk to case: extra weight, can get caught on stuff.
- Paint/coating/PVD on case can scratch/chip with time. Better to avoid to extend usability of watch with respect to appropriate appearance.
- Material:

  - Should be corrosion resistant and have good mechanical properties (not brittle, high strength and toughness, etc.)
  - IMO, since scratches on case do not affect the readability of the watch (unlike scratches on the face), it's not worth forking over large amounts of money for titanium carbide and tungsten carbide (which are more expensive and difficult to work with due to their hardness). Scratches do affect aesthetics of the watch (e.g., when worn with a suit) I suppose, but still not worth paying for harder material, IMO. Plus you can polish/brush out scratches with a softer material anyway.
  - Unless watch is bigger than it should be, weight doesn't matter that much.
  - Stainless steel is perfectly acceptable as a case material (probably makes most sense if you aren't allergic to Nickel). Has desired properties and is cheap and easy-ish to machine.

- Case size: 38-40mm is proably the sweet spot of readability vs bulkiness.

  - Smaller = lighter, less likely to get in the way, impair movement, hit things, etc. But harder to read at a glance.
  - Bigger = easier to read. But heavier, bulkier, etc.

** Crystal

- Worth shelling out for a better crystal material in my opinion. Scratches on face will affect readability of watch over time, particularly with materials that are soft enough to accumulate quite a few scratches.

  - However, as with case material above, most of the softer materials can be polished back to a pristine state, which is something that really hard face materials are incapable of.

- Sapphire crystal is harder than mineral crystal is harder than PMMA.
- PMMA has better mechanical properties than the crystals, which are hard but not /tough/ (meaning they are more prone to shatter under high loads than deform). Highly domed crystals are bad due to the fact that they are constantly under stress from the perimeter to hold them in the watch frame.

** Bezels

- Diving bezel (with minutes)

  - Unecessary on watches with countup (stopwatch) and countdown (timer) functionality -- like that on analog-digital watches.
  - Bidirectional is superior in every situation except for diving. Since dive computers are the norm now, and most peple don't dive anyway, new optimization parameters.
  - Should have ticks all the way around. No reason not to -- enables more precise reading. Having marks in place of big numbers (replacing marks) is preferable.
  - Lume on at least 0, 15, 30, 45. Lume on zero should be brighter/easier to disntiguish.
  - Clicks don't matter from a purely functional point of view. Just one more thing that could break.
  - Bezel should be easy to rotate without being "too" loose.
  - Should have grippable edges of some fashion.
  - Should not significantly add to bulk of watch. It helps to have the watch face (particularly if it is not a scratch-resistant sapphire face) set under the bezel so the bezel can absorb impacts.

** Waterproofing

- Vostok Amphibia with crystal flattening and and increasing WR with increasing pressure -- only possible with PMMA crystal. Quite ingenious and allows for looser tolerances -- but not necessary superior than brute forcing crystal construction in functionality. (Though much more elegant a solution).
- Traditional case-back sealing with o-rings and pressure testing is just silly. Every time watch gets opened, o-ring has to be replaced and watch must be tested (failure = possible repair costs).
- 2-piece locking system with gasket is superior. Reusable, works 100% of the time if assembled correctly. Increasing pressures lead to better sealing. (cf. again Vostok Amphibia's design).
- Theoretically better to have Viton for gaskets/o-rings, but kind of overkill for no very good reason. Would increase prices since compound is proprietary.

** Face

- Dial free from brand name and other info: best readability. Stuff can go on the back of the case.
- Lume works best with thicker hands and hour markers, but it helps to have hands taper to a point to make judging locations easier. Sword shape is the best (straight along length, tapers to point).
- Straighter hands make angles easier to see.
- Don't have hands cover up numbers completely (if you have numbers). It doesn't make sense having the hand cover up the number you want to see. But also balance readability concerns with angles and hour markers.
- Separate rings for hours/minutes (cf. Vasko watches)

  - Clutters face more
  - readability will always be higher without explicit minutes

- The 3, 6, 9 and 12 positions (or 6, 12, 18 and 0 for 24 hour time) should be distinguished from the other hour markers, and 12/0 should be clearly distinguished from the others.
- I advocate not marking numbers explicitly (using only 12 lines/triangles/whatever): same positions are used in distinguishing hours and minutes (so will only get used, at best, in some readings), and numbers will obscure readability in other cases. If you want to mark anything, it should be hours not minutes, because we read a minutes position 23 times every day more than an hour position (at least theoretically). However, see discussion of 12 and 24 hour movements below (reading a 12 hour face with 1-12 numbering as 13-0 will be confusing and unhelpful).
- Minutes hand should be noticeably longer than hours hand. Hours hand should not be too short, however, but easily readable.
- Hands/markings should have high contrast with face. A black face with white marking is optimal since most lume paints on white (or at least a light color).

** Movement

- Quartz mechanism

  - More accurate (less time drift), shock resistant, longer lasting
  - But relies on a battery/capacitor
  - Temperature regulated, selected/calibrated (cf. Seiko 9F) would be best, but not really worth it
  - Still typically 3 seconds/month off. Most mechanicals (even the good ones) are seconds a /day/ off.

- Jeweled movement mechanism

** 12 vs. 24 Hour Format

- Best to have 12 not 24 hour format, but use military time for precision. Accomplish this by practicing reading times before and after noon, with 1:00 --> 13:00 etc. Will take some extra practice to get proficient, but will make telling relative time in hours easier to visualize (since hours won't be so spread out). Get the benefits of increased readability from having a 12 hour format on face, but benefits of 24 hour format from thinking in military time.
- Logic:

  - 12ths are optimal for minutes and seconds (divisions of 5). 12 is also a highly composite number: can be split into halves, thirds, fourths, sixths, and twelfths. Optimal for reading relative time distances in the increments of 15, 20, 30 minutes etc. Also optimal for hours: on a face split into 12ths, 4ths = 3 hours, 3rds = 4 hours, halfs = 6 hours, while on a face split into 24ths 4ths = 6 hours, thirds = 8 hours, halfs = 12 hours.

    - Therefore 12ths should be prominently marked on the dial

  - Most people are not polar explorers or on submarines, so we can distinguish what part of the day we are in. Will be obvious by sun position if outside.
  - Philosophically, it would make sense if the hours hand revolved once every 24 hours
  - However, reading hours in 24 segments will /always/ be more difficult than reading hours in 12 segments due to more precise spatial recognition for the latter (bigger space, more visible, less cluttered/things to mix up).
  - Numbers on face reduce legibility, especially when there are a lot of them. (Both minutes and hours).
  - Without numbers as guides, 24 hour dials make reading hours difficult. (In other words, numbers are necessary for a quick reading of the hours -- practice helps, but doesn't fix the underlying issue).
  - Military time is more precise than AM/PM: no numbers are repeated, which minimizes the likelihood of confusing times (scheduling a flight at 6:30 AM instead of 6:30 PM, e.g.), and there is no ambiguity with 12 AM/12PM.
  - Having multiple numbers on the 12 different locations (e.g., 0100 hours and 1300 hours) will cause extra cognitive load at first, but over time, will become instinctual just like reading time normally.

** Power

- Options: battery, solar, kinetic (i.e., capacitor mechanism powered by movement of body).
- Non-battery options can break (compromise overall longevity of watch if they are made poorly), have to send to "special place" (proprietary service center) to get repaired.
- If battery powered, should be able to take the long-lasting 10+ year batteries. Should be a common, not-proprietary, format.

** Illumination

- Passive illumination: lume and tritium

  - Lume has several advantages over tritium: tritium has a ~12 year half life, making it's usable lifespan within 20 years. Lume paint has a theoretically longer lifespan, and is easier to reapply (than tritium insets).
  - Lume should be applied over as large an area as possible with as many layers as possible (on dial and bezel, if applicable).
  - Prefereably a variety that is bright and long lasting
  - Visibility increased by trying to set the lume to a wavelength close to the number which appears brightest to human eyes (some variety of light green).
  - As with general face design, the 3, 6, 9 and 12 positions (or 6, 12, 18 and 0 for 24 hour time) should be distinguished from the other lumed hour markers, and 12/0 should be clearly distinguished from all the others. Different shapes.

- Also best to have some form of active illumination to light up whole face.

  - Indiglo-esque backlight?
  - Automatic when you bring wrist up (cf. Casio EL)?
  - Balance factors such as lifespan of light, drain on battery, readability, price.
  - Should light evenly.
  - Should not totally nuke night vision.

** Straps

- NATO, without a doubt. More secure, doesn't matter if a spring-bar breaks, extra length means you can put over sleeves etc., easily swappable/replaceable.
- Nylon = easy to clean, strong, can be made to be comfortable.
- Holes should have something to prevent fraying (sonic welding, e.g.).
- Heavy duty, corrosion resistant hardware (e.g., stainless steel).

** Mechanical Watch Specific

- Movement should be hackable (seconds hand stops when crown is pulled out).
- Movement should be automatic, but have option to handwind as well.
- Movement should have ability get regulated if so desired.
- Crown

  - Should /have/ lateral play to remove possiblity of bending stem/putting stress on sensitive movement parts.
  - Should be large enough to comfortably grip, but not unreasonably so
  - Should have some features to make it more grippable

- Complications

  - Date only. Want to keep dial clean and readable.
  - Doesn't really matter where it goes so long as 3, 6, 9, 12 clearly distinguished. Theoretically best in middle.
  - Should have a quick-set option
  - Should be able to set date without adjusting time
  - Keep it simple: no perpetual calendar. More moving parts/possiblity to break.

** Options/Extensibility

- Should have spare parts available along with the watch (spring bars, dials, replacement crystals, bezels, etc.).
- Make as many of the aspects customizable as possible (e.g., lug curvature).
- Design webapp for the the designing of custom faces. Print Lume automatically with specialized printer?

** Todo:

- Jumping hours hand -- saves energy, increases hours readability (at the cost of making incremental time telling with hours hand impossible). Worth?
- Compass bezel to aid in making more efficient directional changes based on bearing shown on watch face (for digital compass watches)
- Think about watch features: stopwatch, countdown, better to have multiple on digital watch, split between two watches?

** My Pick

- [[https://www.amazon.com/gp/product/B00M0ESOCA/][Casio Lineage Solar Multiband 6 Watch]]
